/**
 * OPS Web — Contact-form new-thread draft placement
 *
 * Shared by the sync auto-draft path (sync-engine.maybeAutoGenerateDraft) and
 * the manual Pipeline "Draft" route. When a lead's only inbound correspondence
 * is a forwarded contact-form submission, the form lives on the FORWARDER's
 * thread — a reply addressed to that thread is wrong. Instead we start a clean
 * NEW thread to the actual client, capture the provider-minted thread id, and:
 *   - persist it onto ai_draft_history.thread_id, so reconcilePendingMailboxDrafts
 *     can detect the client's eventual reply (it keys on thread_id);
 *   - link the new thread to the opportunity (opportunity_email_threads), so the
 *     user's send creates an outbound activity reconciliation can read.
 *
 * One predicate, one place — prevents the sync and manual paths from drifting.
 */

import { requireSupabase } from "@/lib/supabase/helpers";
import { pickExistingMailboxDraft, type MailboxDraftRow } from "./mailbox-draft-helpers";
import type { CreateNewThreadDraftResult } from "./email-provider";
import type { ContactFormSubmissionIdentity } from "@/lib/utils/email-parsing";

/** OPS-voice subject for an auto-drafted FIRST reply to a contact-form lead.
 *  Sentence case, no exclamation, no "Re:" (ops-copywriter, 2026-06-03). */
export const CONTACT_FORM_OUTREACH_SUBJECT = "Thanks for reaching out";

/** Grounds the new-email draft in the submitter's actual inquiry so the body
 *  reads as a real first reply, not boilerplate. Fed to generateDraft as
 *  `userInstruction` (its new-email prompt renders it as "Purpose: …"). */
export function buildContactFormDraftInstruction(
  submitter: Pick<ContactFormSubmissionIdentity, "name" | "message">
): string {
  const who = submitter.name?.trim() || "a prospective customer";
  const msg = submitter.message?.trim();
  const quoted = msg ? ` They wrote: "${msg.slice(0, 500)}"` : "";
  return `Write a brief, warm first reply to a new website enquiry from ${who}.${quoted} Acknowledge their request and suggest a next step (a quick call or a site visit). Keep it short and do not invent specifics.`;
}

type PushProvider = {
  createNewThreadDraft: (
    to: string,
    subject: string,
    body: string
  ) => Promise<CreateNewThreadDraftResult>;
  updateDraft: (
    draftId: string,
    to: string,
    subject: string,
    body: string,
    threadId?: string
  ) => Promise<void>;
};

interface PlaceNewThreadDraftArgs {
  provider: PushProvider;
  connectionId: string;
  opportunityId: string;
  /** ai_draft_history row id created by AIDraftService.generateDraft. */
  draftHistoryId: string;
  to: string;
  subject: string;
  body: string;
}

/** A reusable prior draft also carries its minted thread so updateDraft can
 *  re-pin to the same conversation. */
type ReusableDraftRow = MailboxDraftRow & { thread_id?: string | null };

/**
 * Place a fresh-outreach draft on a NEW provider thread for a contact-form lead.
 *
 * Idempotent per (connection_id, opportunity_id): a re-sync reuses the prior
 * auto_drafted mailbox draft (updateDraft on its thread) instead of minting a
 * second thread. May throw — callers run this inside their own non-fatal
 * try/catch (the sync loop and the manual route both treat push as best-effort).
 */
export async function placeNewThreadDraft({
  provider,
  connectionId,
  opportunityId,
  draftHistoryId,
  to,
  subject,
  body,
}: PlaceNewThreadDraftArgs): Promise<{ mailboxDraftId: string; threadId: string | null }> {
  const supabase = requireSupabase();

  // Idempotency: keyed on the opportunity, not a thread — at first run no new
  // thread exists yet, and there is no shared forwarder thread to dedup on.
  const { data: priorRows } = await supabase
    .from("ai_draft_history")
    .select("id, mailbox_draft_id, status, thread_id")
    .eq("connection_id", connectionId)
    .eq("opportunity_id", opportunityId);

  const existing = pickExistingMailboxDraft(
    (priorRows ?? []) as MailboxDraftRow[]
  ) as ReusableDraftRow | null;

  let mailboxDraftId: string;
  let threadId: string | null;

  if (existing?.mailbox_draft_id) {
    const reuseThread = existing.thread_id ?? undefined;
    await provider.updateDraft(existing.mailbox_draft_id, to, subject, body, reuseThread);
    mailboxDraftId = existing.mailbox_draft_id;
    threadId = existing.thread_id ?? null;
  } else {
    const created = await provider.createNewThreadDraft(to, subject, body);
    mailboxDraftId = created.draftId;
    threadId = created.threadId;
  }

  await supabase
    .from("ai_draft_history")
    .update({
      status: "auto_drafted",
      mailbox_draft_id: mailboxDraftId,
      thread_id: threadId,
      subject,
      subject_source: "generated",
    })
    .eq("id", draftHistoryId);

  // Link the new thread to the opportunity so processSentEmail attaches the
  // user's eventual send as an outbound activity (reconciliation reads it) and
  // future client replies inherit the lead.
  if (threadId) {
    await supabase.from("opportunity_email_threads").upsert(
      { opportunity_id: opportunityId, thread_id: threadId, connection_id: connectionId },
      { onConflict: "thread_id,connection_id" }
    );
  }

  return { mailboxDraftId, threadId };
}
