import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import {
  EXTERNAL_API_EXAMPLES,
  generateExternalApiOpenApi,
  serializeExternalApiOpenApi,
} from "../../scripts/generate-external-api-openapi";
import {
  intakeConfigResultSchema,
  submissionRequestSchema,
  submissionResultSchema,
  submissionStatusResultSchema,
  uploadBatchRequestSchema,
  uploadBatchResultSchema,
} from "@/lib/external-api/contracts/intake";
import {
  leadFeedQuerySchema,
  leadFeedResultSchema,
} from "@/lib/external-api/contracts/lead-feed";
import {
  metricQuerySchema,
  metricsResultSchema,
} from "@/lib/external-api/contracts/metrics";
import {
  EXTERNAL_API_REFERENCE_OPERATION_IDS,
  externalApiReference,
} from "@/lib/external-api/docs/reference";

const generatedPath = resolve(process.cwd(), "docs/api/openapi-v1.json");

function operations(document: ReturnType<typeof generateExternalApiOpenApi>) {
  return Object.values(document.paths).flatMap((path) =>
    Object.entries(path).filter(([method]) =>
      ["get", "post", "put", "patch", "delete"].includes(method)
    )
  );
}

function propertyNames(value: unknown, found = new Set<string>()): Set<string> {
  if (Array.isArray(value)) {
    for (const entry of value) propertyNames(entry, found);
    return found;
  }
  if (typeof value !== "object" || value === null) return found;
  for (const [key, entry] of Object.entries(value)) {
    if (
      key === "properties" &&
      typeof entry === "object" &&
      entry !== null &&
      !Array.isArray(entry)
    ) {
      for (const property of Object.keys(entry)) {
        found.add(property.toLowerCase());
      }
    }
    propertyNames(entry, found);
  }
  return found;
}

describe("external API OpenAPI contract", () => {
  it("is generated byte-for-byte from the runtime contract registry", () => {
    expect(readFileSync(generatedPath, "utf8")).toBe(
      serializeExternalApiOpenApi()
    );
  });

  it("publishes exactly six bearer-protected operations and their scopes", () => {
    const document = generateExternalApiOpenApi();
    const published = operations(document);

    expect(published).toHaveLength(6);
    expect(
      published.map(([, operation]) => operation["x-ops-required-scopes"])
    ).toEqual([
      ["intake.write"],
      ["intake.write"],
      ["intake.write"],
      ["intake.write"],
      ["analytics.leads.read"],
      ["analytics.leads.read"],
    ]);
    for (const [, operation] of published) {
      expect(operation.security).toEqual([{ bearerAuth: [] }]);
    }
    expect(
      document.components.securitySchemes.bearerAuth.description
    ).toContain("server-side");
  });

  it("references generated runtime request, response, and safe error schemas", () => {
    const serialized = JSON.stringify(generateExternalApiOpenApi());

    for (const schemaName of [
      "UploadBatchRequest",
      "UploadBatchSuccess",
      "SubmissionRequest",
      "SubmissionSuccess",
      "SubmissionStatusSuccess",
      "LeadFeedQuery",
      "LeadFeedSuccess",
      "MetricQuery",
      "MetricsSuccess",
      "ErrorEnvelope",
    ]) {
      expect(serialized).toContain(`#/components/schemas/${schemaName}`);
    }
  });

  it("keeps analytics schemas free of contact, storage, and internal identity fields", () => {
    const document = generateExternalApiOpenApi();
    const analyticsProperties = propertyNames({
      LeadFeedSuccess: document.components.schemas.LeadFeedSuccess,
      MetricsSuccess: document.components.schemas.MetricsSuccess,
    });

    for (const forbidden of [
      "contact",
      "email",
      "phone",
      "serviceaddress",
      "filename",
      "storageobjectkey",
      "companyid",
      "opportunityid",
      "credentialid",
      "secretdigest",
    ]) {
      expect(analyticsProperties).not.toContain(forbidden);
    }
  });

  it("keeps every published example valid against the same runtime schemas", () => {
    expect(() =>
      intakeConfigResultSchema.parse(EXTERNAL_API_EXAMPLES.intakeConfigResult)
    ).not.toThrow();
    expect(() =>
      uploadBatchRequestSchema.parse(EXTERNAL_API_EXAMPLES.uploadBatchRequest)
    ).not.toThrow();
    expect(() =>
      uploadBatchResultSchema.parse(EXTERNAL_API_EXAMPLES.uploadBatchResult)
    ).not.toThrow();
    expect(() =>
      submissionRequestSchema.parse(EXTERNAL_API_EXAMPLES.submissionRequest)
    ).not.toThrow();
    expect(() =>
      submissionResultSchema.parse(EXTERNAL_API_EXAMPLES.submissionResult)
    ).not.toThrow();
    expect(() =>
      submissionStatusResultSchema.parse(
        EXTERNAL_API_EXAMPLES.submissionStatusResult
      )
    ).not.toThrow();
    expect(() =>
      leadFeedQuerySchema.parse(EXTERNAL_API_EXAMPLES.leadFeedQuery)
    ).not.toThrow();
    expect(() =>
      leadFeedResultSchema.parse(EXTERNAL_API_EXAMPLES.leadFeedResult)
    ).not.toThrow();
    expect(() =>
      metricQuerySchema.parse(EXTERNAL_API_EXAMPLES.metricQuery)
    ).not.toThrow();
    expect(() =>
      metricsResultSchema.parse(EXTERNAL_API_EXAMPLES.metricsResult)
    ).not.toThrow();
  });

  it("keeps the public reference in exact operation coverage with the contract", () => {
    const document = generateExternalApiOpenApi();
    const publishedOperationIds = operations(document).map(
      ([, operation]) => operation.operationId
    );

    expect(publishedOperationIds).toEqual(EXTERNAL_API_REFERENCE_OPERATION_IDS);
    expect(
      externalApiReference.operations.map((operation) => operation.operationId)
    ).toEqual(publishedOperationIds);
    expect(externalApiReference.document).toEqual(document);
  });
});
