select jsonb_build_object(
'observed_at',now(),
'ledger',(select jsonb_agg(jsonb_build_object('version',version,'name',name,'statement_count',cardinality(statements),'sql_sha256',encode(extensions.digest(convert_to(array_to_string(statements,E'\n'),'UTF8'),'sha256'),'hex'))) from supabase_migrations.schema_migrations where name='financial_document_private_drafts'),
'columns',(select jsonb_agg(jsonb_build_object('name',column_name,'type',data_type,'nullable',is_nullable,'default',column_default) order by ordinal_position) from information_schema.columns where table_schema='public' and table_name='estimates' and column_name in ('distribution_hold','document_kind','baseline_estimate_id','currency_code','scope_inclusions','scope_exclusions')),
'private_tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'acl',c.relacl,'anon_select',has_table_privilege('anon',c.oid,'SELECT'),'authenticated_select',has_table_privilege('authenticated',c.oid,'SELECT'),'service_select',has_table_privilege('service_role',c.oid,'SELECT'),'service_insert',has_table_privilege('service_role',c.oid,'INSERT')) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relkind='r' and c.relname like 'financial_document%'),
'functions',(select jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'security_definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl,'definition_md5',md5(pg_get_functiondef(p.oid)),'anon_execute',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated_execute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_execute',has_function_privilege('service_role',p.oid,'EXECUTE')) order by p.oid::regprocedure::text) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('private','public') and p.proname like '%financial_document%'),
'effect_policy',(select jsonb_agg(jsonb_build_object('revision',revision,'stored',effect_revision,'current',private.financial_document_effect_revision(),'matches',effect_revision=private.financial_document_effect_revision())) from private.financial_document_effect_policy),
'estimates',(select jsonb_build_object('count',count(*),'legacy_hash',md5(coalesce(string_agg(md5((to_jsonb(e)-array['distribution_hold','document_kind','baseline_estimate_id','currency_code','scope_inclusions','scope_exclusions'])::text),'' order by id),'')),'held_count',count(*) filter(where distribution_hold),'change_orders',count(*) filter(where document_kind='change_order')) from public.estimates e),
'lines',(select jsonb_build_object('count',count(*),'hash',md5(coalesce(string_agg(md5(to_jsonb(e)::text),'' order by id),''))) from public.line_items e),
'clients',(select jsonb_build_object('count',count(*),'hash',md5(coalesce(string_agg(md5(to_jsonb(e)::text),'' order by client_id),''))) from private.mcp_oauth_clients e),
'grants',(select jsonb_build_object('count',count(*),'hash',md5(coalesce(string_agg(md5(to_jsonb(e)::text),'' order by id),''))) from private.mcp_oauth_grants e),
'dormant',jsonb_build_object('v17_clients',(select count(*) from private.mcp_oauth_clients where exposure_revision='2026-09-07.mcp-exposure.v17'),'v17_grants',(select count(*) from private.mcp_oauth_grants where exposure_revision='2026-09-07.mcp-exposure.v17'),'policies',(select count(*) from private.financial_document_policies),'proposals',(select count(*) from private.financial_document_proposals),'write_tokens',(select count(*) from private.financial_document_write_tokens),'actions',(select count(*) from public.agent_actions where action_type='approve_financial_document')),
'rls_policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname='public' and policyname like 'financial_document_%'),
'constraints',(select jsonb_agg(jsonb_build_object('name',conname,'valid',convalidated,'definition',pg_get_constraintdef(oid))) from pg_constraint where (conrelid='public.estimates'::regclass and (conname like '%document%' or conname like '%baseline%' or conname like '%currency%' or conname like '%custody%')) or (conrelid='private.agent_mcp_rate_limit_buckets'::regclass and conname='agent_mcp_rate_limit_buckets_policy_closed')),
'triggers',(select jsonb_agg(jsonb_build_object('table',tgrelid::regclass::text,'name',tgname,'enabled',tgenabled,'definition',pg_get_triggerdef(oid)) order by tgname) from pg_trigger where tgname in ('estimates_private_draft_custody','line_items_private_draft_custody','accounting_sync_queue_private_drafts'))
) as readback;
