\set ON_ERROR_STOP on
-- Disposable fixture: exact production column types/defaults and NOT NULL constraints.
-- Unrelated foreign keys/checks/triggers are omitted; assignment guard/core are real.
create schema private; create schema auth; create schema extensions;
create extension pgcrypto with schema extensions;
do $$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon;create role authenticated;create role service_role; end if; end $$;
create type public.gmail_connection_type as enum ('company','individual');
create function auth.role() returns text language sql stable as $$ select current_setting('request.jwt.claim.role',true) $$;
set check_function_bodies=off;
create table private.agent_mcp_rate_limit_buckets (
 "bucket_digest" bytea not null,
 "bucket_kind" text not null,
 "policy_id" text not null,
 "window_start" timestamp with time zone not null,
 "units_used" integer default 0 not null,
 "expires_at" timestamp with time zone not null);
create table private.mcp_oauth_clients (
 "client_id" uuid default gen_random_uuid() not null,
 "client_name" text not null,
 "redirect_uris" text[] not null,
 "token_endpoint_auth_method" text not null,
 "grant_types" text[] not null,
 "response_types" text[] not null,
 "scope" text not null,
 "registration_source" text not null,
 "software_id" text,
 "software_version" text,
 "created_at" timestamp with time zone default statement_timestamp() not null,
 "disabled_at" timestamp with time zone,
 "scope_ceiling" text[] not null,
 "consent_catalog_revision" text not null,
 "exposure_revision" text not null);
create table private.mcp_oauth_grants (
 "id" uuid default gen_random_uuid() not null,
 "user_id" uuid not null,
 "company_id" uuid not null,
 "client_id" uuid not null,
 "scopes" text[] not null,
 "revision" text not null,
 "created_at" timestamp with time zone default statement_timestamp() not null,
 "last_used_at" timestamp with time zone,
 "revoked_at" timestamp with time zone,
 "accepted_labels" text[] not null,
 "consent_catalog_revision" text not null,
 "exposure_revision" text not null);
create table private.opportunity_assignment_write_tokens (
 "transaction_id" bigint not null,
 "backend_pid" integer not null,
 "opportunity_id" uuid not null,
 "operation" text not null,
 "assigned_to" uuid,
 "assignment_version" bigint not null,
 "created_at" timestamp with time zone default clock_timestamp() not null);
create table public.accounting_connections (
 "id" uuid default gen_random_uuid() not null,
 "company_id" text not null,
 "provider" text not null,
 "access_token" text,
 "refresh_token" text,
 "token_expires_at" timestamp with time zone,
 "realm_id" text,
 "is_connected" boolean default false not null,
 "last_sync_at" timestamp with time zone,
 "sync_enabled" boolean default false not null,
 "webhook_verifier_token" text,
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null,
 "sync_direction" text default 'pull_only'::text not null,
 "realm_id_lookup" text,
 "propagate_deletes" boolean default false not null,
 "provider_environment" text default 'production'::text not null,
 "sage_business_id" text,
 "sage_business_id_lookup" text,
 "sage_business_name" text);
create table public.activities (
 "id" uuid default gen_random_uuid() not null,
 "company_id" uuid not null,
 "opportunity_id" uuid,
 "client_id" uuid,
 "estimate_id" uuid,
 "invoice_id" uuid,
 "type" text not null,
 "subject" text not null,
 "content" text,
 "outcome" text,
 "direction" text,
 "duration_minutes" integer,
 "created_by" uuid,
 "created_at" timestamp with time zone default now() not null,
 "attachments" text[] default '{}'::text[],
 "email_thread_id" text,
 "email_message_id" text,
 "is_read" boolean default true not null,
 "site_visit_id" uuid,
 "project_id" text,
 "from_email" text,
 "match_confidence" text,
 "match_needs_review" boolean default false not null,
 "suggested_client_id" uuid,
 "to_emails" text[] default '{}'::text[],
 "cc_emails" text[] default '{}'::text[],
 "body_text" text,
 "has_attachments" boolean default false not null,
 "attachment_count" integer default 0 not null,
 "classified_at" timestamp with time zone,
 "classifier_version" text,
 "sent_by_agent" boolean default false not null,
 "attachment_ids" uuid[] default ARRAY[]::uuid[],
 "draft_history_id" uuid,
 "call_source" text,
 "caller_number" text,
 "call_started_at" timestamp with time zone,
 "body_text_clean" text,
 "email_connection_id" uuid,
 "provider_mutations_disabled" boolean default false not null);
create table public.agent_actions (
 "id" uuid default gen_random_uuid() not null,
 "company_id" uuid not null,
 "user_id" uuid not null,
 "action_type" text not null,
 "action_data" jsonb not null,
 "context_summary" text not null,
 "context_source" text,
 "source_id" text,
 "confidence" double precision default 0.5 not null,
 "priority" text default 'normal'::text not null,
 "status" text default 'pending'::text not null,
 "reviewed_by" uuid,
 "reviewed_at" timestamp with time zone,
 "review_notes" text,
 "executed_at" timestamp with time zone,
 "execution_result" jsonb,
 "error" text,
 "expires_at" timestamp with time zone,
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null,
 "auto_execute_at" timestamp with time zone);
create table public.clients (
 "id" uuid default gen_random_uuid() not null,
 "bubble_id" text,
 "company_id" uuid not null,
 "name" text not null,
 "email" text,
 "phone_number" text,
 "notes" text,
 "address" text,
 "latitude" double precision,
 "longitude" double precision,
 "profile_image_url" text,
 "created_at" timestamp with time zone default now(),
 "updated_at" timestamp with time zone default now(),
 "deleted_at" timestamp with time zone,
 "qb_id" text,
 "sage_id" text,
 "pricing_tier" text default 'general'::text not null,
 "merged_into_client_id" uuid);
create table public.companies (
 "id" uuid default gen_random_uuid() not null,
 "bubble_id" text,
 "name" text not null,
 "external_id" text,
 "description" text,
 "website" text,
 "phone" text,
 "email" text,
 "address" text,
 "latitude" double precision,
 "longitude" double precision,
 "open_hour" text,
 "close_hour" text,
 "logo_url" text,
 "default_project_color" text default '#9CA3AF'::text,
 "industries" text[] default '{}'::text[],
 "company_size" text,
 "company_age" text,
 "referral_method" text,
 "account_holder_id" text,
 "admin_ids" text[] default '{}'::text[],
 "seated_employee_ids" text[] default '{}'::text[],
 "max_seats" integer default 10,
 "subscription_status" text,
 "subscription_plan" text,
 "subscription_end" timestamp with time zone,
 "subscription_period" text,
 "trial_start_date" timestamp with time zone,
 "trial_end_date" timestamp with time zone,
 "seat_grace_start_date" timestamp with time zone,
 "has_priority_support" boolean default false,
 "data_setup_purchased" boolean default false,
 "data_setup_completed" boolean default false,
 "data_setup_scheduled" timestamp with time zone,
 "stripe_customer_id" text,
 "subscription_ids_json" text,
 "created_at" timestamp with time zone default now(),
 "updated_at" timestamp with time zone default now(),
 "deleted_at" timestamp with time zone,
 "company_code" text,
 "precise_scheduling_enabled" boolean default false,
 "skip_weekends_in_auto_schedule" boolean default true,
 "weather_dependent" boolean,
 "industry" text default 'trades'::text,
 "client_comms_settings" jsonb default '{"invoice_cover": {"enabled": true, "autonomy": "draft_to_queue", "threshold": 0, "send_delay_minutes": 15}, "status_update": {"cadence": "off", "autonomy": "draft_to_queue", "weekly_day": 1, "send_delay_minutes": 15}, "payment_reminder": {"preset": "standard", "enabled": true, "autonomy": "draft_to_queue", "custom_days": [7, 14, 30, 45], "max_reminders": 4, "send_delay_minutes": 15}, "reschedule_request": {"enabled": true, "autonomy": "draft_to_queue", "behavior": "detect_and_draft", "min_confidence": 0.6, "send_delay_minutes": 15}, "reschedule_requests": {"enabled": true, "min_confidence": 0.6}, "appointment_reminder": {"enabled": true, "autonomy": "draft_to_queue", "lead_days": 1, "include_weather": true, "send_hour_local": 14, "send_delay_minutes": 15}, "comms_wizard_version": 0, "day_before_reminders": {"enabled": true, "send_hour_utc": 14, "include_weather": true}, "appointment_confirmation": {"level": "draft_on_confirm", "confirm_mode": "explicit", "send_delay_minutes": 15, "reschedule_behavior": "draft", "auto_confirm_after_hours": 4}, "appointment_confirmations": {"enabled": true, "delay_hours": 0}, "comms_wizard_completed_at": null, "subcontractor_coordination": {"enabled": false, "trigger": "manual"}}'::jsonb,
 "timezone" text default 'America/Vancouver'::text not null,
 "locale" text default 'en'::text not null,
 "ai_enabled" boolean default true not null,
 "physical_address" text,
 "default_work_start" time without time zone default '08:00:00'::time without time zone not null,
 "default_work_end" time without time zone default '17:00:00'::time without time zone not null,
 "priority_support_period" text,
 "currency_code" text default 'CAD'::text not null,
 "source_app" text default 'ops'::text not null,
 "lifecycle_settings" jsonb,
 "schedule_settings" jsonb default '{"enabled": true, "climate_zone": "auto", "cascade_detection": true, "weather_awareness": true, "conflict_detection": true, "travel_optimization": true, "outdoor_task_type_ids": [], "optimization_window_days": 2}'::jsonb not null,
 "invoice_settings" jsonb default '{"default_tax_rate": 0, "include_cover_email": true, "high_value_threshold": 5000, "default_payment_terms": "NET-30", "financial_intelligence": {"enabled": true, "aging_min_count": 3, "aging_days_threshold": 60, "overdue_pct_threshold": 30, "min_estimates_for_analysis": 5, "concentration_pct_threshold": 40, "win_rate_decrease_threshold": 40, "win_rate_increase_threshold": 80}, "auto_suggest_from_estimate": true, "auto_suggest_on_completion": true}'::jsonb not null,
 "task_groups_conversion_enabled" boolean default false not null,
 "public_handle" text not null);
create table public.email_assignment_contact_form_draft_queue (
 "id" uuid default gen_random_uuid() not null,
 "assignment_event_id" uuid not null,
 "company_id" uuid not null,
 "opportunity_id" uuid not null,
 "assignment_version" bigint not null,
 "actor_user_id" uuid not null,
 "connection_id" uuid not null,
 "source_activity_id" uuid not null,
 "provider_message_id" text not null,
 "source_provider_thread_id" text not null,
 "customer_email" text not null,
 "customer_name" text,
 "source_subject" text not null,
 "source_body_text" text not null,
 "draft_history_id" uuid,
 "reused_from_draft_history_id" uuid,
 "mailbox_draft_id" text,
 "outreach_provider_thread_id" text,
 "provider_create_attempt_id" uuid,
 "provider_create_started_at" timestamp with time zone,
 "status" text default 'pending'::text not null,
 "attempts" integer default 0 not null,
 "available_at" timestamp with time zone default now() not null,
 "lease_holder" text,
 "lease_expires_at" timestamp with time zone,
 "prepared_at" timestamp with time zone,
 "completed_at" timestamp with time zone,
 "result_reason" text,
 "last_error" text,
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null,
 "mailbox_busy_since" timestamp with time zone);
create table public.email_connections (
 "id" uuid default gen_random_uuid() not null,
 "company_id" text not null,
 "type" gmail_connection_type default 'company'::gmail_connection_type not null,
 "user_id" text,
 "email" text not null,
 "access_token" text not null,
 "refresh_token" text not null,
 "expires_at" timestamp with time zone not null,
 "history_id" text,
 "sync_enabled" boolean default true not null,
 "last_synced_at" timestamp with time zone,
 "created_at" timestamp with time zone default now(),
 "updated_at" timestamp with time zone default now(),
 "sync_interval_minutes" integer default 60 not null,
 "sync_filters" jsonb default '{"labelIds": ["INBOX", "SENT"], "excludeDomains": [], "includeSentMail": true, "excludeAddresses": [], "usePresetBlocklist": true, "excludeSubjectKeywords": []}'::jsonb not null,
 "provider" text default 'gmail'::text not null,
 "webhook_subscription_id" text,
 "webhook_expires_at" timestamp with time zone,
 "ops_label_id" text,
 "ai_review_enabled" boolean default false not null,
 "ai_memory_enabled" boolean default false not null,
 "status" text default 'active'::text not null,
 "auto_send_settings" jsonb,
 "archive_writeback_preference" text default 'ask'::text not null,
 "archive_lead_preference" text default 'ask'::text not null,
 "agent_can_send_from" boolean default false not null,
 "sync_in_progress_at" timestamp with time zone,
 "sync_lock_owner" uuid,
 "webhook_client_state_hash" text,
 "history_recovery_anchor" timestamp with time zone,
 "history_recovery_page_token" text,
 "history_recovery_target_token" text,
 "default_intake_owner_id" uuid,
 "outreach_subject" text,
 "signature_logo_url" text,
 "provider_snapshot_at" timestamp with time zone,
 "granted_scopes" text[],
 "webhook_history_high_water" text);
create table public.notifications (
 "id" uuid default gen_random_uuid() not null,
 "user_id" text not null,
 "company_id" text not null,
 "type" text default 'mention'::text not null,
 "title" text not null,
 "body" text not null,
 "project_id" text,
 "note_id" text,
 "is_read" boolean default false not null,
 "created_at" timestamp with time zone default now() not null,
 "expense_id" text,
 "batch_id" text,
 "deep_link_type" text,
 "persistent" boolean default false,
 "action_url" text,
 "action_label" text,
 "dedupe_key" text,
 "resolved_at" timestamp with time zone,
 "resolved_by" uuid,
 "resolution_reason" text,
 "incident_version" bigint default 0 not null);
create table public.opportunities (
 "id" uuid default gen_random_uuid() not null,
 "company_id" uuid not null,
 "client_id" uuid,
 "title" text not null,
 "description" text,
 "contact_name" text,
 "contact_email" text,
 "contact_phone" text,
 "stage" text default 'new_lead'::text not null,
 "source" text,
 "assigned_to" uuid,
 "priority" text,
 "estimated_value" numeric(12,2),
 "actual_value" numeric(12,2),
 "win_probability" integer default 10,
 "expected_close_date" date,
 "actual_close_date" date,
 "stage_entered_at" timestamp with time zone default now() not null,
 "project_id" uuid,
 "lost_reason" text,
 "lost_notes" text,
 "address" text,
 "last_activity_at" timestamp with time zone,
 "next_follow_up_at" timestamp with time zone,
 "tags" text[],
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null,
 "deleted_at" timestamp with time zone,
 "source_email_id" text,
 "client_ref" uuid,
 "project_ref" uuid,
 "quote_delivery_method" text,
 "correspondence_count" integer default 0 not null,
 "outbound_count" integer default 0 not null,
 "inbound_count" integer default 0 not null,
 "last_inbound_at" timestamp with time zone,
 "last_outbound_at" timestamp with time zone,
 "last_message_direction" text,
 "archived_at" timestamp with time zone,
 "stage_manually_set" boolean default false not null,
 "ai_summary" text,
 "images" text[] default '{}'::text[],
 "ai_stage_confidence" double precision,
 "ai_stage_signals" text[],
 "detected_value" integer,
 "latitude" double precision,
 "longitude" double precision,
 "source_message_id" text,
 "source_metadata" jsonb,
 "merged_into_opportunity_id" uuid,
 "source_thread_key" text,
 "assignment_version" bigint default 0 not null,
 "handled_at" timestamp with time zone,
 "ai_summary_updated_at" timestamp with time zone,
 "operator_action_required_at" timestamp with time zone,
 "stage_manual_boundary_event_id" uuid,
 "stage_manual_boundary_at" timestamp with time zone,
 "stage_manual_corrected_at" timestamp with time zone,
 "won_prompt_declined_at" timestamp with time zone,
 "won_prompt_declined_by" uuid);
create table public.opportunity_assignment_deliveries (
 "id" uuid default gen_random_uuid() not null,
 "assignment_event_id" uuid not null,
 "company_id" uuid not null,
 "opportunity_id" uuid not null,
 "assignment_version" bigint not null,
 "recipient_user_id" uuid not null,
 "access_after" boolean not null,
 "notify" boolean not null,
 "state" text default 'pending'::text not null,
 "attempts" integer default 0 not null,
 "available_at" timestamp with time zone default now() not null,
 "claimed_at" timestamp with time zone,
 "claimed_by" text,
 "delivered_at" timestamp with time zone,
 "last_error" text,
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null,
 "lease_token" uuid,
 "lease_expires_at" timestamp with time zone,
 "max_attempts" integer default 8 not null,
 "notification_id" uuid,
 "disposition" text,
 "push_state" text default 'pending'::text not null,
 "terminal_at" timestamp with time zone);
create table public.opportunity_assignment_events (
 "id" uuid default gen_random_uuid() not null,
 "company_id" uuid not null,
 "opportunity_id" uuid not null,
 "previous_assignee_id" uuid,
 "new_assignee_id" uuid,
 "actor_user_id" uuid,
 "source" text not null,
 "suggestion_id" uuid,
 "assignment_version" bigint not null,
 "previous_assignee_snapshot" jsonb,
 "new_assignee_snapshot" jsonb,
 "actor_snapshot" jsonb,
 "metadata" jsonb default '{}'::jsonb not null,
 "created_at" timestamp with time zone default now() not null);
create table public.opportunity_assignment_suggestions (
 "id" uuid default gen_random_uuid() not null,
 "company_id" uuid not null,
 "opportunity_id" uuid not null,
 "suggested_user_id" uuid not null,
 "confidence" double precision not null,
 "reason" text not null,
 "signals" jsonb default '{}'::jsonb not null,
 "generator_version" text not null,
 "generated_at" timestamp with time zone default now() not null,
 "resolution_state" text default 'pending'::text not null,
 "resolved_at" timestamp with time zone,
 "resolved_by" uuid,
 "resolution_event_id" uuid,
 "resolution_metadata" jsonb default '{}'::jsonb not null,
 "created_at" timestamp with time zone default now() not null,
 "updated_at" timestamp with time zone default now() not null);
create table public.role_permissions (
 "id" uuid default gen_random_uuid() not null,
 "role_id" uuid not null,
 "permission" text not null,
 "scope" text default 'all'::text not null,
 "created_at" timestamp with time zone default now() not null);
create table public.roles (
 "id" uuid default gen_random_uuid() not null,
 "name" text not null,
 "hierarchy" integer default 0 not null,
 "created_at" timestamp with time zone default now() not null,
 "description" text,
 "is_preset" boolean default false not null,
 "company_id" uuid,
 "updated_at" timestamp with time zone default now());
create table public.user_permission_overrides (
 "id" uuid default gen_random_uuid() not null,
 "user_id" uuid not null,
 "company_id" uuid not null,
 "permission" text not null,
 "scope" text,
 "granted" boolean default true not null,
 "created_at" timestamp with time zone default now(),
 "updated_at" timestamp with time zone default now());
create table public.user_roles (
 "id" uuid default gen_random_uuid() not null,
 "user_id" text not null,
 "role_id" uuid not null,
 "created_at" timestamp with time zone default now() not null);
create table public.users (
 "id" uuid default gen_random_uuid() not null,
 "bubble_id" text,
 "company_id" uuid,
 "first_name" text not null,
 "last_name" text not null,
 "email" text,
 "phone" text,
 "home_address" text,
 "profile_image_url" text,
 "user_color" text,
 "role" text default 'unassigned'::text,
 "user_type" text,
 "is_company_admin" boolean default false,
 "has_completed_tutorial" boolean default false,
 "dev_permission" boolean default false,
 "latitude" double precision,
 "longitude" double precision,
 "location_name" text,
 "client_id" text,
 "is_active" boolean default true,
 "stripe_customer_id" text,
 "device_token" text,
 "auth_id" text,
 "created_at" timestamp with time zone default now(),
 "updated_at" timestamp with time zone default now(),
 "deleted_at" timestamp with time zone,
 "firebase_uid" text,
 "special_permissions" text[] default '{}'::text[],
 "email_domain_valid" boolean,
 "removed_from_email_list" boolean default false,
 "removed_from_email_list_at" timestamp with time zone,
 "fab_actions" text[],
 "setup_progress" jsonb default '{}'::jsonb,
 "emergency_contact_name" text,
 "emergency_contact_phone" text,
 "emergency_contact_relationship" text,
 "onboarding_completed" jsonb default '{}'::jsonb,
 "onesignal_player_id" text,
 "preferences" jsonb default '{}'::jsonb not null);
alter table private.mcp_oauth_clients add primary key("client_id");
alter table private.mcp_oauth_grants add primary key("id");
alter table public.accounting_connections add primary key("id");
alter table public.activities add primary key("id");
alter table public.agent_actions add primary key("id");
alter table public.clients add primary key("id");
alter table public.companies add primary key("id");
alter table public.email_assignment_contact_form_draft_queue add primary key("id");
alter table public.email_connections add primary key("id");
alter table public.notifications add primary key("id");
alter table public.opportunities add primary key("id");
alter table public.opportunity_assignment_deliveries add primary key("id");
alter table public.opportunity_assignment_events add primary key("id");
alter table public.opportunity_assignment_suggestions add primary key("id");
alter table public.role_permissions add primary key("id");
alter table public.roles add primary key("id");
alter table public.user_permission_overrides add primary key("id");
alter table public.user_roles add primary key("id");
alter table public.users add primary key("id");
alter table public.opportunity_assignment_events add constraint opportunity_assignment_events_source_check check(source <> '');
alter table private.agent_mcp_rate_limit_buckets add constraint agent_mcp_rate_limit_buckets_policy_closed check(policy_id <> '');
alter table public.opportunity_assignment_deliveries add unique(assignment_event_id,recipient_user_id);
alter table public.email_assignment_contact_form_draft_queue add unique(assignment_event_id);
\ir agent-customer-update-prerequisites.sql
\ir agent-customer-update-checks.sql
create trigger trg_opportunities_guard_assignment_mutation before insert or update of assigned_to,assignment_version on public.opportunities for each row execute function private.guard_opportunity_assignment_mutation();
create trigger opportunity_assignment_contact_form_draft_queue after insert on public.opportunity_assignment_events for each row execute function private.queue_email_assignment_contact_form_draft_from_assignment();
create trigger activities_assignment_contact_form_draft_queue after insert on public.activities for each row execute function private.queue_email_assignment_contact_form_draft_from_activity();
\ir agent-customer-update-auth.sql
set check_function_bodies=on;
\ir ../../supabase/migrations/20260904233000_agent_customer_opportunity_update.sql
