-- Real production CHECK constraints read on 2026-09-04.
alter table public.agent_actions add constraint agent_actions_priority_check CHECK ((priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])));
alter table public.agent_actions add constraint agent_actions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'executed'::text, 'failed'::text, 'expired'::text, 'cancelled'::text])));
alter table public.notifications add constraint notification_action_url_internal CHECK (((action_url IS NULL) OR ((action_url <> ''::text) AND (action_url = btrim(action_url)) AND ("left"(action_url, 1) = '/'::text) AND ("left"(action_url, 2) <> '//'::text) AND (POSITION(('\'::text) IN (action_url)) = 0) AND (action_url !~ '[[:cntrl:]]'::text))));
alter table public.notifications add constraint notifications_company_id_canonical CHECK (((company_id IS NULL) OR ((company_id = btrim(company_id, E' \t\n\r'::text)) AND (company_id !~ '[[:cntrl:]]'::text) AND (company_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text)))) NOT VALID;
alter table public.notifications add constraint notifications_incident_version_nonnegative CHECK ((incident_version >= 0));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_assignment_version_check CHECK ((assignment_version > 0));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_attempts_check CHECK ((attempts >= 0));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_disposition_check CHECK (((disposition IS NULL) OR (disposition = ANY (ARRAY['notified'::text, 'silent'::text, 'stale'::text, 'inaccessible'::text, 'terminal_failure'::text]))));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_lease_check CHECK ((((state = 'processing'::text) AND (lease_token IS NOT NULL) AND (lease_expires_at IS NOT NULL)) OR ((state <> 'processing'::text) AND (lease_token IS NULL) AND (lease_expires_at IS NULL))));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_max_attempts_check CHECK (((max_attempts >= 1) AND (max_attempts <= 20)));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_push_state_check CHECK ((push_state = ANY (ARRAY['pending'::text, 'sent'::text, 'suppressed'::text])));
alter table public.opportunity_assignment_deliveries add constraint opportunity_assignment_deliveries_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'processing'::text, 'delivered'::text, 'failed'::text])));
alter table public.opportunity_assignment_events add constraint opportunity_assignment_events_actor_required CHECK (((actor_user_id IS NOT NULL) OR (source = ANY (ARRAY['personal_mailbox'::text, 'company_mailbox_default'::text, 'external_intake_default'::text, 'public_booking_default'::text, 'deactivation'::text, 'permission_change'::text, 'admin_correction'::text, 'system_repair'::text]))));
alter table public.opportunity_assignment_events add constraint opportunity_assignment_events_assignment_version_check CHECK ((assignment_version > 0));
alter table public.opportunity_assignment_events add constraint opportunity_assignment_events_changed CHECK ((previous_assignee_id IS DISTINCT FROM new_assignee_id));
alter table public.opportunity_assignment_suggestions add constraint opportunity_assignment_suggestions_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)));
alter table public.opportunity_assignment_suggestions add constraint opportunity_assignment_suggestions_resolution_shape CHECK ((((resolution_state = 'pending'::text) AND (resolved_at IS NULL) AND (resolved_by IS NULL) AND (resolution_event_id IS NULL)) OR ((resolution_state <> 'pending'::text) AND (resolved_at IS NOT NULL))));
alter table public.opportunity_assignment_suggestions add constraint opportunity_assignment_suggestions_resolution_state_check CHECK ((resolution_state = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'invalidated'::text, 'superseded'::text])));
