-- Run after bootstrap + actual ownership triggers + migration in a disposable DB.
select test.assert(to_regprocedure('public.finalize_exact_email_thread_recovery_guarded(uuid,uuid,uuid,uuid,text,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb,jsonb)') is not null,'exact recovery finalization RPC must exist');

create function test.reset() returns void language plpgsql as $$
declare company uuid='10000000-0000-4000-8000-000000000001'; actor uuid='20000000-0000-4000-8000-000000000001'; connection uuid='30000000-0000-4000-8000-000000000001'; owner uuid='40000000-0000-4000-8000-000000000001'; source uuid='50000000-0000-4000-8000-000000000001'; target uuid='50000000-0000-4000-8000-000000000002'; i integer;
begin
  truncate private.email_thread_recovery_finalizations,private.email_exact_message_recovery_applications,private.opportunity_child_reparent_tokens,public.activities,public.opportunity_correspondence_events,public.email_attachments,public.email_attachment_scans,public.email_attachment_inspection_jobs,public.email_conversion_photo_jobs,public.email_conversion_photo_objects,public.email_threads,public.opportunity_email_threads,public.opportunities,public.email_connections,public.users,public.companies,private.email_provider_mailbox_sync_leases,test.config;
  perform set_config('test.role','service_role',false);
  perform set_config('test.mailbox_allowed','true',false);
  perform set_config('test.edit_allowed','true',false);
  perform set_config('test.pipeline_scope','all',false);
  insert into public.companies values(company);
  insert into public.users values(actor,company,null,true);
  insert into public.email_connections values(connection,company::text,'active','gmail','operator@example.test',true,owner,clock_timestamp());
  insert into private.email_provider_mailbox_sync_leases values(connection,owner,clock_timestamp()+interval '5 minutes');
  insert into public.opportunities values
    (source,company,'60000000-0000-4000-8000-000000000001','60000000-0000-4000-8000-000000000001','referrer@example.test','Referrer Customer','Finished job','won',true,actor,7,'70000000-0000-4000-8000-000000000001','70000000-0000-4000-8000-000000000001','2026-08-01',null,null,'old-job','2026-09-11'),
    (target,company,null,null,'customer@example.test','Referred Customer','New request','new_lead',false,actor,1,null,null,null,null,null,'email:gmail:'||connection||':message:message-3','2026-09-11');
  insert into public.email_threads values('80000000-0000-4000-8000-000000000001',company,connection,'referral-thread',source,'60000000-0000-4000-8000-000000000001','2026-09-12','2026-09-11','New deck',4,'Original snippet');
  insert into public.opportunity_email_threads values('90000000-0000-4000-8000-000000000001',connection,'referral-thread',source,'2026-09-11');
  for i in 1..4 loop
    insert into public.activities values(('a0000000-0000-4000-8000-00000000000'||i)::uuid,company,connection,'referral-thread','message-'||i,target,'email',case when i%2=0 then 'outbound' else 'inbound' end,case when i=3 then 'customer@example.test' else 'operator@example.test' end,array['customer@example.test'],'{}','Original body '||i,'2026-09-11'::timestamptz+i*interval '1 hour');
    insert into public.opportunity_correspondence_events select ('b0000000-0000-4000-8000-00000000000'||i)::uuid,company,connection,'referral-thread','message-'||i,target,id,direction,case when direction='inbound' then 'customer' else 'operator' end,true,true,email_from,email_to,email_cc,created_at from public.activities where email_message_id='message-'||i;
    insert into private.email_exact_message_recovery_applications select company,connection,'message-'||i,'referral-thread',source,target,a.id,e.id,'customer@example.test',actor,repeat('a',64),repeat(i::text,64),case when i=3 then 'created' end,case when i=3 then 'email:gmail:'||connection||':message:message-3' end,case when i=3 then 'New request' end,case when i=3 then 'Referred Customer' end,'complete',0,1,'{}',now(),now() from public.activities a join public.opportunity_correspondence_events e on e.activity_id=a.id where a.email_message_id='message-'||i;
    insert into public.email_attachment_scans select ('c1000000-0000-4000-8000-00000000000'||i)::uuid,company,connection,'referral-thread','message-'||i,a.id,'complete',1 from public.activities a where a.email_message_id='message-'||i;
  end loop;
  insert into public.email_attachments select 'c0000000-0000-4000-8000-000000000003',company,connection,'referral-thread','message-3',a.id,'attributed',target,'stored' from public.activities a where a.email_message_id='message-3';
  insert into public.email_attachment_inspection_jobs values('d0000000-0000-4000-8000-000000000003','c0000000-0000-4000-8000-000000000003','complete');
  insert into public.email_conversion_photo_jobs values('e0000000-0000-4000-8000-000000000003','c0000000-0000-4000-8000-000000000003','complete','revoke');
  insert into public.email_conversion_photo_objects values('f0000000-0000-4000-8000-000000000003','e0000000-0000-4000-8000-000000000003','deleted');
  update private.email_exact_message_recovery_applications set attachment_count=1,attachment_ids=array['c0000000-0000-4000-8000-000000000003'::uuid] where provider_message_id='message-3';
  insert into test.config select jsonb_build_object('actor',actor,'company',company,'connection',connection,'owner',owner,'thread','referral-thread','source',source,'target',target,'email','customer@example.test','manifest',repeat('f',64),'evidence',(select jsonb_agg(jsonb_build_object('provider_message_id',provider_message_id,'activity_id',activity_id,'correspondence_event_id',correspondence_event_id,'manifest_sha256',manifest_sha256,'entry_sha256',entry_sha256) order by provider_message_id) from private.email_exact_message_recovery_applications),'source_snapshot',(select to_jsonb(o) from public.opportunities o where id=source),'target_snapshot',(select to_jsonb(o) from public.opportunities o where id=target),'thread_snapshot',(select to_jsonb(t) from public.email_threads t),'link_snapshot',(select to_jsonb(l) from public.opportunity_email_threads l),'activities',(select jsonb_agg(to_jsonb(a) order by id) from public.activities a),'events',(select jsonb_agg(to_jsonb(e) order by id) from public.opportunity_correspondence_events e));
end $$;

create function test.call(overrides jsonb default '{}') returns jsonb language plpgsql as $$ declare p jsonb; begin
 select value||overrides into p from test.config;
 return public.finalize_exact_email_thread_recovery_guarded((p->>'actor')::uuid,(p->>'company')::uuid,(p->>'connection')::uuid,(p->>'owner')::uuid,p->>'thread',(p->>'source')::uuid,(p->>'target')::uuid,p->>'email',p->>'manifest',p->'evidence',p->'source_snapshot',p->'target_snapshot',p->'thread_snapshot',p->'link_snapshot');
end $$;

select test.reset();
select test.assert((test.call()->>'already_finalized')::boolean=false,'first application');
select test.assert((test.call()->>'already_finalized')::boolean=true,'exact replay');
select test.assert((select count(*)=1 from private.email_thread_recovery_finalizations),'one immutable receipt');
select test.assert((select t.opportunity_id=(c.value->>'target')::uuid and t.client_id is null and t.archived_at='2026-09-12'::timestamptz and t.latest_snippet='Original snippet' from public.email_threads t cross join test.config c),'target routing and archive preservation');
select test.assert((select to_jsonb(o)=c.value->'source_snapshot' from public.opportunities o cross join test.config c where o.id=(c.value->>'source')::uuid),'won source fully unchanged');
select test.assert((select to_jsonb(o)=c.value->'target_snapshot' from public.opportunities o cross join test.config c where o.id=(c.value->>'target')::uuid),'target identity and assignment fully unchanged');
select test.assert((select jsonb_agg(to_jsonb(a) order by id)=(select value->'activities' from test.config) from public.activities a),'immutable activities');
select test.assert((select jsonb_agg(to_jsonb(e) order by id)=(select value->'events' from test.config) from public.opportunity_correspondence_events e),'immutable correspondence');
select test.assert((select count(*)=0 from private.opportunity_child_reparent_tokens),'tokens consumed');
select test.assert(coalesce(current_setting('ops.email_thread_reassignment_mode',true),'')='','context restored');
select test.expect_error('select test.call(''{"manifest":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}'')','finalization_replay_conflict');

select test.reset();
select set_config('test.role','authenticated',false);
select test.expect_error('select test.call()','access_denied');
select test.reset();
select set_config('test.mailbox_allowed','false',false);
select test.expect_error('select test.call()','finalization_actor_denied');
select test.reset();
select set_config('test.edit_allowed','false',false);
select test.expect_error('select test.call()','finalization_actor_denied');
select test.reset();
update public.users set is_active=false;
select test.expect_error('select test.call()','finalization_actor_denied');
select test.reset();
update private.email_provider_mailbox_sync_leases set expires_at=now()-interval '1 second';
select test.expect_error('select test.call()','finalization_lease_changed');
select test.reset();
select test.expect_error('select test.call(''{"owner":"40000000-0000-4000-8000-000000000009"}'')','finalization_lease_changed');
select test.reset();
update private.email_exact_message_recovery_applications set actor_user_id='20000000-0000-4000-8000-000000000009' where provider_message_id='message-2';
select test.expect_error('select test.call()','finalization_evidence_mismatch');
select test.reset();
update private.email_exact_message_recovery_applications set status='attachment_pending' where provider_message_id='message-4';
select test.expect_error('select test.call()','finalization_evidence_mismatch');
select test.reset();
update public.email_attachment_scans set status='pending' where message_id='message-3';
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update public.email_attachments set attribution_status='needs_review';
select test.expect_error('select test.call()','exact_recovery_attachment_needs_review');
select test.reset();
update public.activities set opportunity_id='50000000-0000-4000-8000-000000000001' where email_message_id='message-4';
select test.expect_error('select test.call()','finalization_message_ownership_mismatch');
select test.reset();
update public.opportunity_correspondence_events set opportunity_id='50000000-0000-4000-8000-000000000001' where provider_message_id='message-2';
select test.expect_error('select test.call()','finalization_message_ownership_mismatch');
select test.reset();
insert into public.activities select 'a0000000-0000-4000-8000-000000000009',company_id,email_connection_id,email_thread_id,'message-new',opportunity_id,type,direction,email_from,email_to,email_cc,body_text,created_at from public.activities limit 1;
select test.expect_error('select test.call()','finalization_message_set_mismatch');
select test.reset();
insert into public.opportunity_correspondence_events select 'b0000000-0000-4000-8000-000000000009',company_id,connection_id,provider_thread_id,'message-new',opportunity_id,activity_id,direction,party_role,is_meaningful,opportunity_projection_applied,from_email,to_emails,cc_emails,occurred_at from public.opportunity_correspondence_events limit 1;
select test.expect_error('select test.call()','finalization_message_set_mismatch');
select test.reset();
insert into public.email_attachments select 'c0000000-0000-4000-8000-000000000001',company_id,email_connection_id,email_thread_id,email_message_id,id,'attributed',opportunity_id,'discovered' from public.activities limit 1;
select test.expect_error('select test.call()','finalization_attachment_set_changed');
select test.reset();
update public.email_attachment_scans set generation=2 where message_id='message-3';
select test.expect_error('select test.call()','exact_recovery_attachment_scan_generation_changed');
select test.reset();
delete from public.email_attachment_scans where message_id='message-1';
select test.expect_error('select test.call()','exact_recovery_attachment_scan_missing');
select test.reset();
update public.email_attachment_scans set status='failed' where message_id='message-3';
select test.expect_error('select test.call()','exact_recovery_attachment_scan_failed');
select test.reset();
update public.email_attachment_inspection_jobs set status='pending';
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update public.email_attachment_inspection_jobs set status='failed';
select test.expect_error('select test.call()','exact_recovery_attachment_inspection_failed');
select test.reset();
delete from public.email_attachment_inspection_jobs;
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update public.email_conversion_photo_jobs set status='pending';
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update public.email_conversion_photo_jobs set status='failed';
select test.expect_error('select test.call()','exact_recovery_attachment_materialization_failed');
select test.reset();
update public.email_conversion_photo_objects set state='uploaded';
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update public.email_attachments set opportunity_id='50000000-0000-4000-8000-000000000001';
select test.expect_error('select test.call()','finalization_attachments_incomplete');
select test.reset();
update private.email_exact_message_recovery_applications set entry_sha256=repeat('9',64) where provider_message_id='message-1';
select test.expect_error('select test.call()','finalization_evidence_mismatch');
select test.reset();
select set_config('test.pipeline_scope','assigned',false);
select test.expect_error('select test.call()','finalization_actor_denied');
select test.reset();
update public.opportunities set assignment_version=assignment_version+1 where contact_email='customer@example.test';
select test.expect_error('select test.call()','finalization_opportunity_snapshot_changed');
select test.reset();
update public.opportunities set contact_name='Changed Customer' where contact_email='customer@example.test';
select test.expect_error('select test.call()','finalization_opportunity_snapshot_changed');
select test.reset();
update public.opportunities set stage='lost' where stage='won';
select test.expect_error('select test.call()','finalization_opportunity_snapshot_changed');
select test.reset();
update public.opportunities set project_id='70000000-0000-4000-8000-000000000002' where stage='won';
select test.expect_error('select test.call()','finalization_opportunity_snapshot_changed');
select test.reset();
update public.email_threads set archived_at=null;
select test.expect_error('select test.call()','finalization_thread_snapshot_changed');
select test.reset();
select test.expect_error('select test.call(jsonb_build_object(''evidence'',(select value->''evidence'' from test.config)||jsonb_build_array((select value->''evidence''->0 from test.config))))','invalid_finalization_evidence');
select test.reset();
select test.expect_error('select test.call(''{"email":"unproven@example.test"}'')','finalization_target_identity_mismatch');

-- Force a failure after the canonical link write; both updates and all tokens
-- must roll back, while an outer caller's guard context must survive unchanged.
create function test.fail_thread_update() returns trigger language plpgsql as $$ begin raise exception 'injected_thread_failure'; end $$;
create trigger z_test_fail before update on public.email_threads for each row execute function test.fail_thread_update();
select set_config('ops.email_thread_reassignment_mode','outer-context',false);
select test.expect_error('select test.call()','injected_thread_failure');
select test.assert((select to_jsonb(l)=c.value->'link_snapshot' from public.opportunity_email_threads l cross join test.config c),'partial failure link rollback');
select test.assert((select count(*)=0 from private.email_thread_recovery_finalizations),'partial failure receipt rollback');
select test.assert((select count(*)=0 from private.opportunity_child_reparent_tokens),'failure token cleanup');
select test.assert(current_setting('ops.email_thread_reassignment_mode')='outer-context','failure outer context preserved');
drop trigger z_test_fail on public.email_threads;
select test.assert((test.call()->>'already_finalized')::boolean=false,'retry after rollback succeeds');
select test.assert(current_setting('ops.email_thread_reassignment_mode')='outer-context','success outer context preserved');
select test.assert(not has_function_privilege('authenticated','public.finalize_exact_email_thread_recovery_guarded(uuid,uuid,uuid,uuid,text,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb,jsonb)','execute'),'authenticated cannot execute');
select test.assert(not has_table_privilege('service_role','private.email_thread_recovery_finalizations','update'),'service cannot edit receipt');
select test.assert(not has_function_privilege('anon','public.finalize_exact_email_thread_recovery_guarded(uuid,uuid,uuid,uuid,text,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb,jsonb)','execute'),'anon cannot execute');
select test.assert((select relrowsecurity from pg_class where oid='private.email_thread_recovery_finalizations'::regclass),'private ledger RLS enabled');

-- An expiry occurring inside an otherwise successful update must roll back.
select test.reset();
create function test.expire_lease() returns trigger language plpgsql as $$ begin update private.email_provider_mailbox_sync_leases set expires_at=clock_timestamp()-interval '1 second'; return new; end $$;
create trigger z_test_expire after update on public.email_threads for each row execute function test.expire_lease();
select test.expect_error('select test.call()','finalization_lease_changed');
select test.assert((select to_jsonb(l)=c.value->'link_snapshot' from public.opportunity_email_threads l cross join test.config c),'expired lease rolls back link');
select test.assert((select count(*)=0 from private.email_thread_recovery_finalizations),'expired lease creates no receipt');
drop trigger z_test_expire on public.email_threads;
select 'EXACT_THREAD_FINALIZATION_CONTRACTS_PASSED' as proof;
