\set ON_ERROR_STOP on
-- Disposable fixture only; columns/checks below are from read-only Supabase metadata 2026-09-12.
-- Live postgres defaults verified 2026-09-15: identity sequences inherit these
-- grants independently of their parent table. The migration must remove them.
alter default privileges in schema public grant all on sequences to anon,authenticated,service_role;
create table public.projects (id uuid primary key,company_id uuid not null,title text not null,status text not null,deleted_at timestamptz);
create table public.expense_categories (id uuid primary key, company_id uuid);
create table public.accounting_connections (
  id uuid default gen_random_uuid() not null,
  company_id text not null,
  provider text not null,
  access_token text,
  refresh_token text,
  token_expires_at timestamptz,
  realm_id text,
  is_connected bool default false not null,
  last_sync_at timestamptz,
  sync_enabled bool default false not null,
  webhook_verifier_token text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  sync_direction text default 'pull_only'::text not null,
  realm_id_lookup text,
  propagate_deletes bool default false not null,
  provider_environment text default 'production'::text not null,
  sage_business_id text,
  sage_business_id_lookup text,
  sage_business_name text,
  constraint accounting_connections_company_provider_environment_key UNIQUE (company_id, provider, provider_environment),
  constraint accounting_connections_pkey PRIMARY KEY (id),
  constraint accounting_connections_provider_environment_check CHECK ((provider_environment = ANY (ARRAY['production'::text, 'sandbox'::text]))),
  constraint accounting_connections_sage_business_binding_check CHECK (((provider <> 'sage'::text) OR (is_connected = false) OR ((NULLIF(btrim(sage_business_id), ''::text) IS NOT NULL) AND (sage_business_id_lookup ~ '^[0-9a-f]{64}$'::text) AND (NULLIF(btrim(sage_business_name), ''::text) IS NOT NULL)))),
  constraint accounting_connections_sync_direction_check CHECK ((sync_direction = ANY (ARRAY['pull_only'::text, 'push_only'::text, 'bidirectional'::text])))
);
create table public.accounting_sync_queue (
  id uuid default gen_random_uuid() not null,
  company_id uuid not null,
  connection_id uuid not null,
  provider text default 'quickbooks'::text not null,
  entity_type text not null,
  entity_id uuid not null,
  external_id text,
  operation text not null,
  source_table text not null,
  source_action text not null,
  source_updated_at timestamptz,
  idempotency_key text not null,
  status text default 'pending'::text not null,
  attempts int4 default 0 not null,
  max_attempts int4 default 5 not null,
  run_after timestamptz default now() not null,
  locked_at timestamptz,
  locked_by text,
  last_error text,
  payload_snapshot jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  provider_request_id text,
  provider_accepted_at timestamptz,
  idempotency_expires_at timestamptz,
  constraint accounting_sync_queue_attempts_check CHECK ((attempts >= 0)),
  constraint accounting_sync_queue_entity_type_check CHECK ((entity_type = ANY (ARRAY['customer'::text, 'invoice'::text, 'estimate'::text, 'payment'::text, 'supplier'::text, 'supplier_bill'::text, 'supplier_bill_payment'::text]))),
  constraint accounting_sync_queue_max_attempts_check CHECK ((max_attempts > 0)),
  constraint accounting_sync_queue_operation_check CHECK ((operation = ANY (ARRAY['create'::text, 'update'::text, 'void'::text, 'inactivate'::text, 'delete_soft'::text, 'delete'::text, 'link'::text, 'reconcile'::text]))),
  constraint accounting_sync_queue_pkey PRIMARY KEY (id),
  constraint accounting_sync_queue_provider_check CHECK ((provider = ANY (ARRAY['quickbooks'::text, 'sage'::text]))),
  constraint accounting_sync_queue_provider_evidence_check CHECK ((((provider_accepted_at IS NULL) AND (idempotency_expires_at IS NULL)) OR ((provider_accepted_at IS NOT NULL) AND (idempotency_expires_at IS NOT NULL) AND (idempotency_expires_at > provider_accepted_at)))),
  constraint accounting_sync_queue_source_action_check CHECK ((source_action = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text, 'soft_delete'::text, 'void'::text]))),
  constraint accounting_sync_queue_source_table_check CHECK ((source_table = ANY (ARRAY['clients'::text, 'sub_clients'::text, 'invoices'::text, 'estimates'::text, 'payments'::text, 'line_items'::text, 'suppliers'::text, 'supplier_bills'::text, 'supplier_bill_payments'::text]))),
  constraint accounting_sync_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'claimed'::text, 'succeeded'::text, 'failed'::text, 'blocked'::text, 'needs_review'::text, 'cancelled'::text])))
);
create table public.accounting_sync_events (
  id uuid default gen_random_uuid() not null,
  queue_id uuid,
  company_id uuid not null,
  connection_id uuid,
  provider text default 'quickbooks'::text not null,
  direction text not null,
  entity_type text not null,
  entity_id text,
  external_id text,
  operation text not null,
  status text not null,
  source text not null,
  ops_updated_at timestamptz,
  qb_updated_at timestamptz,
  decision text,
  before_snapshot jsonb default '{}'::jsonb not null,
  after_snapshot jsonb default '{}'::jsonb not null,
  error text,
  created_at timestamptz default now() not null,
  constraint accounting_sync_events_decision_check CHECK (((decision IS NULL) OR (decision = ANY (ARRAY['ops_won'::text, 'qb_won'::text, 'sage_won'::text, 'skipped'::text, 'needs_review'::text, 'retry'::text, 'blocked'::text])))),
  constraint accounting_sync_events_direction_check CHECK ((direction = ANY (ARRAY['ops_to_qb'::text, 'qb_to_ops'::text, 'ops_to_sage'::text, 'sage_to_ops'::text, 'reconcile'::text, 'system'::text]))),
  constraint accounting_sync_events_entity_type_check CHECK ((entity_type = ANY (ARRAY['customer'::text, 'invoice'::text, 'estimate'::text, 'payment'::text, 'supplier'::text, 'supplier_bill'::text, 'supplier_bill_payment'::text]))),
  constraint accounting_sync_events_operation_check CHECK ((operation = ANY (ARRAY['create'::text, 'update'::text, 'void'::text, 'inactivate'::text, 'delete_soft'::text, 'delete'::text, 'link'::text, 'reconcile'::text]))),
  constraint accounting_sync_events_pkey PRIMARY KEY (id),
  constraint accounting_sync_events_provider_check CHECK ((provider = ANY (ARRAY['quickbooks'::text, 'sage'::text]))),
  constraint accounting_sync_events_source_check CHECK ((source = ANY (ARRAY['trigger'::text, 'worker'::text, 'webhook'::text, 'reconcile'::text, 'operator'::text, 'system'::text]))),
  constraint accounting_sync_events_status_check CHECK ((status = ANY (ARRAY['succeeded'::text, 'failed'::text, 'blocked'::text, 'needs_review'::text, 'skipped'::text])))
);
grant usage on schema public, private to service_role;
grant all on public.accounting_sync_queue,public.accounting_sync_events,public.accounting_connections to service_role;
