-- Live catalog capture 2026-09-07. Disposable fixture; business rows are fictional.
create table public.accounting_sync_events (
id uuid default gen_random_uuid() not null,
queue_id uuid,
company_id uuid not null,
connection_id uuid,
provider text default 'quickbooks'::text not null,
direction text not null,
entity_type text not null,
entity_id text,
external_id text,
operation text not null,
status text not null,
source text not null,
ops_updated_at timestamp with time zone,
qb_updated_at timestamp with time zone,
decision text,
before_snapshot jsonb default '{}'::jsonb not null,
after_snapshot jsonb default '{}'::jsonb not null,
error text,
created_at timestamp with time zone default now() not null
);
create table public.accounting_sync_queue (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
connection_id uuid not null,
provider text default 'quickbooks'::text not null,
entity_type text not null,
entity_id uuid not null,
external_id text,
operation text not null,
source_table text not null,
source_action text not null,
source_updated_at timestamp with time zone,
idempotency_key text not null,
status text default 'pending'::text not null,
attempts integer default 0 not null,
max_attempts integer default 5 not null,
run_after timestamp with time zone default now() not null,
locked_at timestamp with time zone,
locked_by text,
last_error text,
payload_snapshot jsonb default '{}'::jsonb not null,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now() not null,
provider_request_id text,
provider_accepted_at timestamp with time zone,
idempotency_expires_at timestamp with time zone
);
create table public.accounting_sync_suppressions (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
provider text default 'quickbooks'::text not null,
entity_type text not null,
entity_id uuid not null,
source text default 'quickbooks'::text not null,
expires_at timestamp with time zone default (now() + '00:10:00'::interval) not null,
created_at timestamp with time zone default now() not null
);
create table public.catalog_items (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
category_id uuid,
name text not null,
description text,
default_price numeric,
default_unit_cost numeric,
default_warning_threshold double precision,
default_critical_threshold double precision,
default_unit_id uuid,
image_url text,
notes text,
is_active boolean default true not null,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now() not null,
deleted_at timestamp with time zone,
external_source text,
external_id text
);
create table public.catalog_units (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
display text not null,
abbreviation text,
dimension text default 'count'::text not null,
is_default boolean default false not null,
sort_order integer default 0 not null,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now() not null,
deleted_at timestamp with time zone
);
create table public.document_sequences (
company_id uuid not null,
document_type text not null,
prefix text not null,
last_number bigint default 0 not null,
fiscal_year integer default EXTRACT(year FROM CURRENT_DATE) not null
);
create table public.estimates (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
opportunity_id uuid,
client_id uuid not null,
estimate_number text not null,
version integer default 1 not null,
parent_id uuid,
title text,
client_message text,
internal_notes text,
terms text,
subtotal numeric(12,2) default 0 not null,
discount_type text,
discount_value numeric(12,2),
discount_amount numeric(12,2) default 0 not null,
tax_rate numeric(6,4),
tax_amount numeric(12,2) default 0 not null,
total numeric(12,2) default 0 not null,
deposit_type text,
deposit_value numeric(12,2),
deposit_amount numeric(12,2),
status text default 'draft'::text not null,
issue_date date default CURRENT_DATE not null,
expiration_date date,
sent_at timestamp with time zone,
viewed_at timestamp with time zone,
approved_at timestamp with time zone,
pdf_storage_path text,
created_by uuid,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now() not null,
deleted_at timestamp with time zone,
project_id text,
client_ref uuid,
project_ref uuid,
qb_id text,
template_id uuid,
sage_id text,
notes text,
sage_document_kind text
);
create table public.line_items (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
estimate_id uuid,
invoice_id uuid,
product_id uuid,
name text not null,
description text,
quantity numeric(10,3) default 1 not null,
unit text default 'each'::text,
unit_price numeric(12,2) default 0 not null,
unit_cost numeric(12,2),
discount_percent numeric(5,2) default 0,
is_taxable boolean default true,
tax_rate_id uuid,
is_optional boolean default false,
is_selected boolean default true,
sort_order integer default 0 not null,
category text,
service_date date,
created_at timestamp with time zone default now(),
type text default 'LABOR'::text not null,
task_type_id text,
estimated_hours numeric(6,2),
task_type_ref uuid,
parent_line_item_id uuid,
unit_id uuid,
configured_options jsonb,
resolved_unit_price numeric,
resolved_options_label text,
minimum_charge_snapshot numeric(14,2),
line_total numeric generated always as (round(GREATEST(((quantity * unit_price) * ((1)::numeric - (COALESCE(discount_percent, (0)::numeric) / (100)::numeric))), COALESCE(minimum_charge_snapshot, (0)::numeric)), 2)) stored
);
create table public.products (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
name text not null,
description text,
default_price numeric(12,2) default 0 not null,
unit_cost numeric(12,2),
unit text default 'each'::text,
category text,
is_taxable boolean default true,
is_active boolean default true,
created_at timestamp with time zone default now(),
updated_at timestamp with time zone default now(),
deleted_at timestamp with time zone,
type text default 'LABOR'::text not null,
task_type_id text,
task_type_ref uuid,
unit_id uuid,
kind text default 'service'::text not null,
sku text,
is_favorite boolean default false not null,
minimum_charge numeric,
minimum_quantity numeric,
show_bom_on_estimate boolean default false not null,
show_in_storefront boolean default false not null,
tiered_pricing jsonb default '{}'::jsonb not null,
base_price numeric default 0 not null,
pricing_unit text default 'each'::text not null,
category_id uuid,
thumbnail_url text,
linked_catalog_item_id uuid,
bundle_pricing_mode text,
external_source text,
external_id text
);
create table public.project_notes (
id uuid default gen_random_uuid() not null,
project_id text not null,
company_id text not null,
author_id text not null,
content text default ''::text not null,
attachments jsonb default '[]'::jsonb not null,
mentioned_user_ids text[] default '{}'::text[] not null,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now(),
deleted_at timestamp with time zone,
photo_url text,
event_kind text,
content_metadata jsonb
);
create table public.projects (
id uuid default gen_random_uuid() not null,
bubble_id text,
company_id uuid not null,
client_id uuid,
title text not null,
address text,
latitude double precision,
longitude double precision,
status text default 'rfq'::text not null,
notes text,
description text,
all_day boolean default false,
project_images text[] default '{}'::text[],
team_member_ids text[] default '{}'::text[],
opportunity_id text,
start_date timestamp with time zone,
end_date timestamp with time zone,
duration integer,
created_at timestamp with time zone default now(),
updated_at timestamp with time zone default now(),
deleted_at timestamp with time zone,
completed_at timestamp with time zone,
visibility text default 'all'::text,
trade text,
created_by uuid,
vinyl_order_status text default 'not_ordered'::text,
vinyl_ordered_at timestamp with time zone,
vinyl_ordered_by uuid,
estimated_value numeric,
source text,
platform_metadata jsonb,
opportunity_ref uuid,
priority_rank double precision,
title_is_auto boolean default false not null,
vinyl_color text,
vinyl_po text,
status_version bigint default 0 not null,
vinyl_source text,
primary_sub_client_id uuid
);
create table public.tax_rates (
id uuid default gen_random_uuid() not null,
company_id uuid not null,
name text not null,
rate numeric(6,4) not null,
is_default boolean default false,
is_active boolean default true,
created_at timestamp with time zone default now()
);
