import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const syncEngineSource = readFileSync(
  join(process.cwd(), "src/lib/api/services/sync-engine.ts"),
  "utf8"
);
const emailSyncCronSource = readFileSync(
  join(process.cwd(), "src/app/api/cron/email-sync/route.ts"),
  "utf8"
);

describe("sync-engine Phase C routing boundary", () => {
  it("never invokes or implements the legacy connection-owner auto-draft path", () => {
    expect(syncEngineSource).not.toContain("maybeAutoGenerateDraft");
    expect(syncEngineSource).not.toContain(
      'import { AutoSendService } from "./auto-send-service"'
    );
    expect(syncEngineSource).not.toContain(
      'import { AIDraftService } from "./ai-draft-service"'
    );
  });

  it("defers canonical thread routing to the bounded cron-owned queue", () => {
    expect(syncEngineSource).not.toContain(
      "await EmailThreadService.classifyAndUpdate(threadRow)"
    );
    expect(syncEngineSource).not.toContain(
      "await PhaseCAutonomyRouter.route(threadRow)"
    );
    expect(emailSyncCronSource).toContain(
      "await EmailThreadService.retryDirtyClassifications({"
    );
  });

  it("never treats a shared mailbox connector user as the Phase C learner", () => {
    expect(syncEngineSource).toMatch(
      /connection\.type === "individual"\s*&&\s*connection\.userId/
    );
  });
});
