/**
 * OPS Web — Company Data Manifest
 *
 * The single, authoritative inventory of every table that holds data belonging
 * to one company. `/api/data/export` and `/api/data/delete-account` are both
 * driven by it; neither route names a table anywhere else.
 *
 * ── Why this exists ────────────────────────────────────────────────────────
 * Both routes used to carry their own hardcoded list, frozen years ago. They
 * addressed `estimate_line_items`, `invoice_line_items` and `tasks` — none of
 * which have ever existed (the real tables are `line_items` and
 * `project_tasks`) — and swallowed each per-table error, so account deletion
 * answered "success" while leaving virtually all modern data behind, and every
 * export silently omitted tasks and line items (bug 241830b2).
 *
 * ── Absence is never an exclusion ──────────────────────────────────────────
 * Every table the live schema places inside a company's data is accounted for
 * here — either classified below, or declared in `OUT_OF_SCOPE_TABLES` with a
 * reason. A reader must never have to guess whether a missing table was
 * considered and rejected or simply overlooked; that ambiguity IS the bug this
 * file exists to kill, so the two states are made distinguishable by
 * construction.
 *
 * `tests/integration/company-data-manifest.test.ts` enforces it with two
 * guards of unequal strength.
 *
 * PRIMARY — against `company-data-scope-snapshot.ts`, a checked-in picture of
 * the live schema generated by the documented SQL (tables with `company_id`,
 * plus every base table reaching one through a declared foreign key, to
 * fixpoint):
 *
 *   1. Every table in `IN_SCOPE_SNAPSHOT` MUST appear in the manifest or in
 *      `OUT_OF_SCOPE_TABLES`.
 *   2. The manifest MUST NOT name anything outside `IN_SCOPE_SNAPSHOT`, apart
 *      from `TENANT_TABLE` — no query can derive the company row, since it has
 *      neither a `company_id` nor a foreign key into scope, so the manifest
 *      adds it explicitly as the root.
 *   3. Every table in `AUTH_IDENTITY_SNAPSHOT` MUST be declared out of scope.
 *      These hang off Supabase Auth identities rather than `public.users`, so
 *      the closure cannot reach them even though they look user-owned; naming
 *      them forces a deliberate decision instead of a silent omission.
 *
 * SECONDARY — against the checked-in generated types,
 * `src/lib/types/database.types.ts`: every table in its `Tables:` block that
 * carries a `company_id` must be classified, and the manifest must not name a
 * table the types do not know, except the documented
 * `UNTYPED_TABLE_ALLOWLIST`. This guard is deliberately the weaker of the two
 * — it CANNOT see the backend tables the generated types have not caught up to
 * (every one of them is enumerated in `UNTYPED_TABLE_ALLOWLIST` below), so a
 * table absent from the types could slip past it unnoticed. It must never be
 * the only guard; the snapshot is what actually holds the line.
 *
 * That allowlist shrinks as main regenerates the types, and the
 * stale-allowlist assertion is what forces it to be pruned — treat a failure
 * there as the guard working, not as breakage.
 *
 * Tests cannot reach production, so refreshing those two checked-in artefacts
 * is what forces a new table to be consciously classified. After any migration
 * that adds a company-scoped table, regenerate BOTH the snapshot (see
 * `company-data-scope-snapshot.ts` for the exact queries) and the types; the
 * completeness tests then fail until the table is given a strategy and an
 * export decision here, or an explicit reason for being excluded.
 *
 * ── Derived from the live schema ───────────────────────────────────────────
 * Classification was derived against prod (`ijeekuhbatykdomumfjx`) on
 * 2026-07-29. Three queries reproduce it:
 *
 *   -- 1. every company-scoped base table, its tenant column type, and whether
 *   --    it can be tombstoned at all
 *   SELECT c.table_name, c.data_type, EXISTS (
 *            SELECT 1 FROM information_schema.columns d
 *            WHERE d.table_schema = 'public' AND d.table_name = c.table_name
 *              AND d.column_name = 'deleted_at')
 *   FROM information_schema.columns c
 *   JOIN information_schema.tables t
 *     ON t.table_schema = c.table_schema AND t.table_name = c.table_name
 *    AND t.table_type = 'BASE TABLE'
 *   WHERE c.table_schema = 'public' AND c.column_name = 'company_id';
 *
 *   -- 2. tables with NO company_id that hang off a company-scoped parent by
 *   --    foreign key (invisible to a company_id-only sweep)
 *   -- 3. blocking (NO ACTION / RESTRICT) foreign keys between them, which fix
 *   --    the deletion order and expose the two mutual cycles
 *
 * At the time of writing that is 218 in-scope tables — 180 carrying
 * `company_id` and 38 reaching one by foreign key — plus the `companies` row
 * itself, and 5 auth-identity tables declared out of scope.
 *
 * ── How to classify a new table ────────────────────────────────────────────
 * `export: true`  — the customer's own business records: jobs, tasks, clients,
 *                   money documents, catalog and pricing, photos, notes, site
 *                   visits, leads, calendar, expenses, settings.
 * `export: false` — machinery the system created to run itself: queues,
 *                   outboxes, claims, locks, staging, provider bookkeeping,
 *                   agent internals, telemetry, delivery receipts. Anything
 *                   holding a credential (OAuth tokens, portal tokens) is
 *                   ALWAYS `export: false`.
 * `deleteStrategy` follows the schema: `soft` when the table has a `deleted_at`
 *                   column, `hard` when it does not. `retain` is reserved for
 *                   the handful of rows with a legal, financial or referential
 *                   reason to outlive the account — each carries its reason.
 *
 * Every `retain` and every `export: false` entry states why, in `reason`.
 *
 * ── Deletion ordering ──────────────────────────────────────────────────────
 * `COMPANY_SCOPED_DATA` is ordered, and the order is load-bearing: a hard
 * DELETE fails if a surviving row still references the target. Entries are
 * grouped by foreign-key depth, deepest first, so children are always purged
 * before their parents, and `companies` is tombstoned last. The groups (each
 * derived from prod `pg_constraint`, blocking edges only) are:
 *
 *   depth 5  email_outbound_edit_promotions
 *   depth 4  email_outbound_learning_queue
 *   depth 3  email_conversion_photo_objects, email_send_intents
 *   depth 2  approved_action_email_intents,
 *            email_assignment_contact_form_draft_queue,
 *            email_conversion_photo_jobs, opportunity_assignment_deliveries,
 *            pending_auto_sends
 *   depth 1  activities, agent_knowledge_graph, agent_memories,
 *            attachment_inspections, email_attachments,
 *            email_import_provider_operations, line_items,
 *            opportunity_assignment_events,
 *            opportunity_conversion_notification_deliveries, portal_sessions,
 *            task_schedule_automation_outbox,
 *            unassigned_lead_assignment_deliveries
 *   depth 0  everything else, then `companies`
 *
 * Two pairs reference each other, so no ordering can satisfy both directions.
 * `FK_CYCLE_BREAKERS` nulls the nullable side of each cycle first — on rows
 * that are about to be deleted anyway — which turns each cycle into a chain.
 *
 * Verified 2026-07-29: with this classification, zero surviving rows anywhere
 * in `public` hold a blocking foreign key into a table this manifest purges.
 *
 * NEVER import this from client-side code.
 */

/** Bumped whenever the classification changes. Emitted in both route payloads. */
export const MANIFEST_VERSION = "2026-08-01";

/** The tenant row itself — tombstoned last, scoped by `id` rather than `company_id`. */
export const TENANT_TABLE = "companies";

/**
 * Parent ids are pushed into PostgREST `in.()` filters, which travel in the URL.
 * 500 keeps the request well inside every proxy's URL limit.
 */
export const ID_CHUNK_SIZE = 500;

export type DeleteStrategy = "soft" | "hard" | "retain";

interface ManifestEntryBase {
  readonly table: string;
  /** True only when the table actually has a `deleted_at` column. */
  readonly softDeletable: boolean;
  readonly deleteStrategy: DeleteStrategy;
  /** Is this the customer's own data, or machinery that runs the product? */
  readonly export: boolean;
  /** Required for every `retain` entry and every `export: false` entry. */
  readonly reason?: string;
}

export interface CompanyScopedEntry extends ManifestEntryBase {
  readonly scope: "company";
  /** `company_id` everywhere except the tenant row itself, which uses `id`. */
  readonly companyColumn: string;
  /** The column's Postgres type. The value passed is a string either way. */
  readonly companyColumnType: "uuid" | "text";
}

export interface ParentScopedEntry extends ManifestEntryBase {
  readonly scope: "parent";
  /** The company-scoped (or itself parent-scoped) table this hangs off. */
  readonly parentTable: string;
  /** The NOT NULL foreign-key column on THIS table pointing at the parent. */
  readonly parentColumn: string;
}

export type ManifestEntry = CompanyScopedEntry | ParentScopedEntry;

export type TransactionalPurgeStep = ManifestEntry & {
  readonly definer_purged: boolean;
};

export interface TransactionalPurgePlan {
  readonly manifest_version: string;
  readonly cycle_breakers: typeof FK_CYCLE_BREAKERS;
  readonly steps: readonly TransactionalPurgeStep[];
}

/**
 * A table the live schema puts near a company's data that this cascade
 * deliberately does NOT touch. Declaring it is the point: an excluded table
 * must be a reviewable decision, never an omission.
 */
export interface OutOfScopeEntry {
  readonly table: string;
  /** Why it is not a company's data. Required — there are no silent exclusions. */
  readonly reason: string;
}

/**
 * Mutual foreign-key cycles. Both columns are nullable, and every row touched
 * here is deleted moments later, so nulling them destroys nothing.
 */
export const FK_CYCLE_BREAKERS = [
  {
    table: "pending_auto_sends",
    column: "send_intent_id",
    companyColumn: "company_id",
  },
  {
    table: "opportunity_assignment_suggestions",
    column: "resolution_event_id",
    companyColumn: "company_id",
  },
] as const;

/**
 * A table `service_role` is not permitted to purge directly, and the reason.
 * The cascade routes these through `public.purge_company_rows` instead.
 */
export interface DefinerPurgedEntry {
  readonly table: string;
  /** Why the direct path is unavailable. Required — there are no silent detours. */
  readonly reason: string;
}

/** The SECURITY DEFINER function that purges the tables below. */
export const DEFINER_PURGE_FUNCTION = "purge_company_rows";

/** The single transactional account-deletion entry point. */
export const COMPANY_DATA_PURGE_FUNCTION = "purge_company_data";

/**
 * Tables the cascade cannot delete from directly, because `service_role` — the
 * role both data routes run as — lacks the privilege.
 *
 * ── Why these exist ────────────────────────────────────────────────────────
 * Classification in this manifest says what a table IS. It says nothing about
 * whether the deleting role may touch it. Thirty `public` base tables withhold
 * from `service_role` at least one privilege the cascade needs — fifteen were
 * created by migrations that granted it nothing at all, fifteen more grant
 * SELECT and withhold DELETE. A rehearsal of the cascade against a disposable
 * prod tenant died at
 * acting-step 23 of 198 on the first of them, and would have died on the next
 * fourteen one at a time.
 *
 * The remedy is `public.purge_company_rows(p_table text, p_company_id uuid)` —
 * SECURITY DEFINER, owned by `postgres`, `search_path` pinned, EXECUTE granted
 * to `service_role` only. It refuses any table not on its own allowlist
 * (`42501`) and a NULL company (`22004`), casts the parameter rather than the
 * column so the `company_id` index still applies, and returns the row count.
 * The privilege it lends is exactly "delete one company's rows from one
 * allowlisted table" — narrower, and far more auditable, than granting DELETE
 * on append-only event tables to every service-role code path in the product.
 *
 * ── Invariants ─────────────────────────────────────────────────────────────
 * The function purges by `company_id` and hard-deletes, so every entry here
 * MUST be `scope: "company"`, `companyColumn: "company_id"`, and
 * `deleteStrategy: "hard"`. `tests/integration/company-data-manifest.test.ts`
 * pins that, pins this set against the live privilege snapshot in both
 * directions, and fails the moment a manifest table becomes unpurgeable
 * without being declared here.
 *
 * Entries are grouped by failure shape because the two are diagnosed
 * differently — the first group cannot even be counted, the second counts fine
 * and refuses the DELETE one call later.
 */
export const DEFINER_PURGED_TABLES: readonly DefinerPurgedEntry[] = [
  // ── No privileges at all: SELECT, UPDATE and DELETE are all denied. ───────
  // Granted to `postgres` only. The cascade cannot so much as count these.
  {
    table: "email_assignment_contact_form_draft_queue",
    reason:
      "Granted to postgres only — service_role holds no SELECT, UPDATE or DELETE, so the cascade cannot even count the rows. Purged through purge_company_rows.",
  },
  {
    table: "email_import_provider_operations",
    reason:
      "Granted to postgres only — service_role holds no privileges on the provider-operation log. Purged through purge_company_rows.",
  },
  {
    table: "email_outbound_edit_evidence",
    reason:
      "Granted to postgres only — service_role holds no privileges on the outbound edit-evidence store. Purged through purge_company_rows.",
  },
  {
    table: "email_outbound_edit_promotions",
    reason:
      "Granted to postgres only — service_role holds no privileges. This is the table the live rehearsal died on at step 23 of 198. Purged through purge_company_rows.",
  },
  {
    table: "email_outbound_learning_queue",
    reason:
      "Granted to postgres only — service_role holds no privileges on the outbound learning queue. Purged through purge_company_rows.",
  },
  {
    table: "email_outbound_memory_evidence",
    reason:
      "Granted to postgres only — service_role holds no privileges on the outbound memory-evidence store. Purged through purge_company_rows.",
  },
  {
    table: "email_outbound_writing_samples",
    reason:
      "Granted to postgres only — service_role holds no privileges on the stored writing samples. Purged through purge_company_rows.",
  },
  {
    table: "email_provider_mutation_attempts",
    reason:
      "Granted to postgres only — service_role holds no privileges on the provider mutation-attempt log. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_conversion_notification_deliveries",
    reason:
      "Granted to postgres only — service_role holds no privileges on these delivery receipts. Purged through purge_company_rows.",
  },
  {
    table: "phase_c_category_auto_send_acceptances",
    reason:
      "Granted to postgres only — service_role holds no privileges on the auto-send acceptance ledger. Purged through purge_company_rows.",
  },
  {
    table: "project_status_lifecycle_outbox",
    reason:
      "Granted to postgres only — service_role holds no privileges on the project-status outbox. Purged through purge_company_rows.",
  },
  {
    table: "task_mutation_events",
    reason:
      "Granted to postgres only — service_role holds no privileges on the task mutation event log. Purged through purge_company_rows.",
  },
  {
    table: "task_schedule_automation_outbox",
    reason:
      "Granted to postgres only — service_role holds no privileges on the schedule-automation outbox. Purged through purge_company_rows.",
  },
  {
    table: "unassigned_lead_assignment_deliveries",
    reason:
      "Granted to postgres only — service_role holds no privileges on these delivery receipts. Purged through purge_company_rows.",
  },
  {
    table: "user_permission_change_deliveries",
    reason:
      "Granted to authenticated and postgres — service_role was left out entirely, so it holds no privileges. Purged through purge_company_rows.",
  },

  // ── Readable but not deletable: SELECT granted, DELETE withheld. ──────────
  // These are the dangerous half. The count succeeds, so nothing looks wrong
  // until the DELETE one call later is refused.
  {
    table: "email_conversion_photo_jobs",
    reason:
      "service_role may SELECT but not DELETE — the count succeeds and the purge is refused one call later. Purged through purge_company_rows.",
  },
  {
    table: "email_conversion_photo_objects",
    reason:
      "service_role may SELECT but not DELETE the conversion photo objects. Purged through purge_company_rows.",
  },
  {
    table: "email_ingestion_recovery_queue",
    reason:
      "service_role may SELECT and UPDATE but not DELETE the ingestion recovery queue. Purged through purge_company_rows.",
  },
  {
    table: "email_send_intents",
    reason:
      "service_role may SELECT and UPDATE but not DELETE send intents — the cycle breaker that nulls pending_auto_sends.send_intent_id still works, the purge does not. Purged through purge_company_rows.",
  },
  {
    table: "email_signature_notification_lifecycle_outbox",
    reason:
      "service_role may SELECT but not DELETE the signature-notification outbox. Purged through purge_company_rows.",
  },
  {
    table: "email_signatures",
    reason:
      "service_role may SELECT but not DELETE signatures. The export still works — it only reads — but the purge does not. Purged through purge_company_rows.",
  },
  {
    table: "lead_intake_correction_runs",
    reason:
      "service_role may SELECT but not DELETE intake correction runs. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_assignment_deliveries",
    reason:
      "service_role may SELECT but not DELETE these delivery receipts. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_assignment_events",
    reason:
      "service_role may SELECT but not DELETE the append-only assignment event log. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_assignment_suggestions",
    reason:
      "service_role may SELECT and UPDATE but not DELETE suggestions — the cycle breaker that nulls resolution_event_id still works, the purge does not. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_conversion_events",
    reason:
      "service_role may SELECT but not DELETE the append-only conversion event log. Purged through purge_company_rows.",
  },
  {
    table: "opportunity_manual_outbound_cycle_receipts",
    reason:
      "service_role may SELECT but not DELETE the manual outbound cycle receipt ledger. Purged through purge_company_rows.",
  },
  {
    table: "project_note_mention_events",
    reason:
      "service_role may SELECT but not DELETE the mention event log. Purged through purge_company_rows.",
  },
  {
    table: "stage_transitions",
    reason:
      "service_role may SELECT but not DELETE the append-only stage transition history. The export still works; the purge does not. Purged through purge_company_rows.",
  },
  {
    table: "user_email_aliases",
    reason:
      "service_role may SELECT but not DELETE staff email aliases. The export still works; the purge does not. Purged through purge_company_rows.",
  },
];

let definerPurgedCache: Set<string> | null = null;

/** Must this table's purge go through `public.purge_company_rows`? */
export function isDefinerPurged(table: string): boolean {
  if (!definerPurgedCache) {
    definerPurgedCache = new Set(DEFINER_PURGED_TABLES.map((e) => e.table));
  }
  return definerPurgedCache.has(table);
}

export const PARENT_SCOPED_DATA: readonly ParentScopedEntry[] = [
  {
    table: "catalog_item_tags",
    scope: "parent",
    parentTable: "catalog_items",
    parentColumn: "catalog_item_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "catalog_option_values",
    scope: "parent",
    parentTable: "catalog_options",
    parentColumn: "option_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_options",
    scope: "parent",
    parentTable: "catalog_items",
    parentColumn: "catalog_item_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_order_items",
    scope: "parent",
    parentTable: "catalog_orders",
    parentColumn: "order_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "catalog_snapshot_items",
    scope: "parent",
    parentTable: "catalog_snapshots",
    parentColumn: "snapshot_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "catalog_variant_option_values",
    scope: "parent",
    parentTable: "catalog_variants",
    parentColumn: "variant_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "email_log",
    scope: "parent",
    parentTable: "users",
    parentColumn: "user_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS campaign and onboarding email send log. user_id is nullable, so rows with no user attribution are outside any company's scope by definition.",
  },
  {
    table: "expense_auto_approve_rule_members",
    scope: "parent",
    parentTable: "expense_auto_approve_rules",
    parentColumn: "rule_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "expense_project_allocations",
    scope: "parent",
    parentTable: "expenses",
    parentColumn: "expense_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "line_item_answers",
    scope: "parent",
    parentTable: "line_item_questions",
    parentColumn: "question_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "line_item_materials",
    scope: "parent",
    parentTable: "line_items",
    parentColumn: "line_item_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "opportunity_email_threads",
    scope: "parent",
    parentTable: "opportunities",
    parentColumn: "opportunity_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Lead-to-thread index for the inbox engine.",
  },
  {
    table: "payment_milestones",
    scope: "parent",
    parentTable: "estimates",
    parentColumn: "estimate_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "product_materials",
    scope: "parent",
    parentTable: "products",
    parentColumn: "product_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "product_option_values",
    scope: "parent",
    parentTable: "product_options",
    parentColumn: "option_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "product_options",
    scope: "parent",
    parentTable: "products",
    parentColumn: "product_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "product_pricing_modifiers",
    scope: "parent",
    parentTable: "products",
    parentColumn: "product_id",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "product_tax_rates",
    scope: "parent",
    parentTable: "products",
    parentColumn: "product_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "role_permissions",
    scope: "parent",
    parentTable: "roles",
    parentColumn: "role_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "spec_acceptance_events",
    scope: "parent",
    parentTable: "users",
    parentColumn: "accepted_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_blocked_buyers",
    scope: "parent",
    parentTable: "users",
    parentColumn: "blocked_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_change_orders",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_communications",
    scope: "parent",
    parentTable: "users",
    parentColumn: "logged_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_email_outbox",
    scope: "parent",
    parentTable: "users",
    parentColumn: "recipient_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_feature_acceptance",
    scope: "parent",
    parentTable: "users",
    parentColumn: "verified_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_internal_notes",
    scope: "parent",
    parentTable: "users",
    parentColumn: "created_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_owner_approval_requests",
    scope: "parent",
    parentTable: "users",
    parentColumn: "account_holder_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_payments",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_projects",
    scope: "parent",
    parentTable: "users",
    parentColumn: "buyer_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_referrals",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_refund_requests",
    scope: "parent",
    parentTable: "users",
    parentColumn: "processed_by_user_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_retainers",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_satisfaction_ratings",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_scope_documents",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "spec_support_tickets",
    scope: "parent",
    parentTable: "spec_projects",
    parentColumn: "spec_project_id",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger — contract acceptance, Stripe payments, refunds and the abuse blocklist. It is OPS's own commercial record of a completed sale, not the trades company's operating data, and it must survive account closure for financial, legal and anti-abuse reasons. Every table in the family is declared here rather than left implied.",
  },
  {
    table: "task_materials",
    scope: "parent",
    parentTable: "project_tasks",
    parentColumn: "task_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "task_recurrence_exceptions",
    scope: "parent",
    parentTable: "task_recurrences",
    parentColumn: "recurrence_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "user_roles",
    scope: "parent",
    parentTable: "roles",
    parentColumn: "role_id",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
];

export const COMPANY_SCOPED_DATA: readonly CompanyScopedEntry[] = [
  {
    table: "email_outbound_edit_promotions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound learning promotions.",
  },
  {
    table: "email_outbound_learning_queue",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound learning work queue.",
  },
  {
    table: "email_conversion_photo_objects",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Conversion bookkeeping that pins email_attachments, email_conversion_photo_jobs and opportunity_conversion_events by NOT NULL RESTRICT foreign keys. It carries a deleted_at column, but tombstoning it would force the OAuth-bearing email machinery to be retained forever, so it is purged outright.",
  },
  {
    table: "email_send_intents",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound send-intent machinery.",
  },
  {
    table: "approved_action_email_intents",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound send-intent machinery.",
  },
  {
    table: "email_assignment_contact_form_draft_queue",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Draft-generation work queue.",
  },
  {
    table: "email_conversion_photo_jobs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Lead-to-project photo conversion job queue.",
  },
  {
    table: "opportunity_assignment_deliveries",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Assignment notification delivery receipts.",
  },
  {
    table: "pending_auto_sends",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Auto-send work queue.",
  },
  {
    table: "activities",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "agent_knowledge_graph",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Agent-derived knowledge graph, rebuildable machinery.",
  },
  {
    table: "agent_memories",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Agent memory store, rebuildable machinery.",
  },
  {
    table: "attachment_inspections",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Attachment scanning machinery.",
  },
  {
    table: "email_attachments",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Attachment index for the inbox engine.",
  },
  {
    table: "email_import_provider_operations",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Provider API call bookkeeping.",
  },
  {
    table: "line_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "opportunity_assignment_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Assignment routing machinery.",
  },
  {
    table: "opportunity_conversion_notification_deliveries",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Conversion notification delivery receipts.",
  },
  {
    table: "portal_sessions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Client-portal session records.",
  },
  {
    table: "task_schedule_automation_outbox",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Schedule automation outbox.",
  },
  {
    table: "unassigned_lead_assignment_deliveries",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Assignment notification delivery receipts.",
  },
  {
    table: "accept_estimate_to_job_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Idempotency records for the estimate-to-job accept RPC.",
  },
  {
    table: "accounting_category_mappings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "accounting_connections",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Holds accounting-provider OAuth tokens and realm ids.",
  },
  {
    table: "accounting_sync_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Accounting sync event log.",
  },
  {
    table: "accounting_sync_log",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Accounting sync run log.",
  },
  {
    table: "accounting_sync_queue",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Accounting push/pull work queue.",
  },
  {
    table: "accounting_sync_suppressions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Echo-suppression bookkeeping for accounting sync.",
  },
  {
    table: "activity_comments",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "admin_feature_overrides",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS-side feature flag overrides, not customer data.",
  },
  {
    table: "agent_actions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Inbox agent action log.",
  },
  {
    table: "agent_writing_profiles",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Derived writing-style profile for the inbox agent.",
  },
  {
    table: "ai_draft_history",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Machine-generated draft history; the sent mail is in email_threads.",
  },
  {
    table: "analytics_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Product telemetry, not customer data.",
  },
  {
    table: "app_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Product telemetry, not customer data.",
  },
  {
    table: "audit_log",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Security and compliance audit trail; an audit log must outlive the actions it records, including this deletion.",
  },
  {
    table: "beta_access_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS intake record for beta access requests.",
  },
  {
    table: "billing_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "retain",
    export: true,
    reason:
      "Financial ledger of Stripe charges and refunds; retained for accounting, tax and dispute obligations after the account closes.",
  },
  {
    table: "bug_reports",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS support intake queue.",
  },
  {
    table: "calendar_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "calendar_user_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_categories",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_guided_setup_actions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Guided catalog setup transcript.",
  },
  {
    table: "catalog_guided_setup_sessions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Guided catalog setup session state.",
  },
  {
    table: "catalog_inventory_import_rows",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Inventory import staging rows.",
  },
  {
    table: "catalog_inventory_imports",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Inventory import run bookkeeping.",
  },
  {
    table: "catalog_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_orders",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_product_capability_bindings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_product_option_mappings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_setup_save_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Idempotency records for catalog setup saves.",
  },
  {
    table: "catalog_setup_session_locks",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Concurrency locks for catalog setup.",
  },
  {
    table: "catalog_setup_verification_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Catalog setup checklist state.",
  },
  {
    table: "catalog_snapshots",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "catalog_stock_unit_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "catalog_stock_units",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_supplier_cost_profiles",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_tags",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_units",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "catalog_variants",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "client_product_overrides",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "clients",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "company_default_products",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "company_inventory_settings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "company_settings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "data_setup_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Onboarding data-setup request queue.",
  },
  {
    table: "deck_designs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "deck_subscriptions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: false,
    reason:
      "Decks subscription state mirrored from Stripe; the billing history is in billing_events.",
  },
  {
    table: "deck_zoning_parcel_records",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "document_sequences",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Estimate and invoice numbering counters.",
  },
  {
    table: "document_templates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "duplicate_reviews",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Duplicate-lead review queue.",
  },
  {
    table: "email_attachment_inspection_jobs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Attachment inspection job queue.",
  },
  {
    table: "email_attachment_scans",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Attachment scan results.",
  },
  {
    table: "email_autonomy_milestones",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Inbox autonomy progression state.",
  },
  {
    table: "email_connection_lifecycle_outbox",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Connection lifecycle notification outbox.",
  },
  {
    table: "email_connections",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Holds mailbox OAuth refresh tokens; must never leave the system in an export.",
  },
  {
    table: "email_ingest_heartbeat_log",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Ingest heartbeat telemetry.",
  },
  {
    table: "email_ingestion_recovery_queue",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Ingest recovery work queue.",
  },
  {
    table: "email_oauth_states",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OAuth state nonces.",
  },
  {
    table: "email_outbound_edit_evidence",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound learning evidence.",
  },
  {
    table: "email_outbound_memory_evidence",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Outbound learning evidence.",
  },
  {
    table: "email_outbound_writing_samples",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Derived writing samples for the inbox agent.",
  },
  {
    table: "email_provider_mutation_attempts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Provider mutation attempt log.",
  },
  {
    table: "email_signature_notification_lifecycle_outbox",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Notification outbox.",
  },
  {
    table: "email_signatures",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "email_templates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "email_thread_category_corrections",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Classifier correction feedback.",
  },
  {
    table: "email_threads",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "estimates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "expense_auto_approve_rules",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "expense_batches",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "retain",
    export: true,
    reason:
      "Soft-deleted expenses keep a NOT-ENFORCEABLE-IF-PURGED foreign key to their batch; hard-deleting batches while those tombstones survive would violate referential integrity. Retained so the tombstoned expense records stay readable.",
  },
  {
    table: "expense_categories",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "retain",
    export: true,
    reason:
      "Soft-deleted expenses and recurring_expenses still reference their category; purging categories would break those surviving tombstones. Retained so the expense history stays readable.",
  },
  {
    table: "expense_settings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "expenses",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "feature_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS product-feedback intake.",
  },
  {
    table: "follow_ups",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "forecast_alerts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Derived weather alerts, recomputable.",
  },
  {
    table: "gmail_import_jobs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Mailbox import job queue.",
  },
  {
    table: "gmail_scan_jobs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Mailbox scan job queue.",
  },
  {
    table: "graph_entities",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Agent knowledge-graph entities, rebuildable machinery.",
  },
  {
    table: "inventory_deductions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "invoices",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "lead_classification_reviews",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Classifier review queue.",
  },
  {
    table: "lead_disposition_feedback",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Classifier training feedback.",
  },
  {
    table: "lead_field_provenance",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Field-level extraction provenance.",
  },
  {
    table: "lead_intake_correction_runs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Lead intake correction runs.",
  },
  {
    table: "lead_lifecycle_settings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "line_item_questions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "notification_preferences",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "notifications",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "In-app notification rail rows, superseded by the records they point at.",
  },
  {
    table: "onboarding_email_log",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS onboarding drip send log.",
  },
  {
    table: "opportunities",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "opportunity_assignment_suggestions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Machine-generated assignment suggestions.",
  },
  {
    table: "opportunity_conversion_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Lead-to-project conversion machinery.",
  },
  {
    table: "opportunity_manual_outbound_cycle_receipts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Idempotency receipts for manual outbound opportunity-cycle bookkeeping.",
  },
  {
    table: "opportunity_correspondence_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Correspondence tracking machinery.",
  },
  {
    table: "opportunity_dispositions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "opportunity_follow_up_drafts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Machine-generated follow-up drafts.",
  },
  {
    table: "opportunity_lifecycle_action_audit",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Lifecycle action machinery audit.",
  },
  {
    table: "opportunity_lifecycle_state",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Derived lifecycle state, recomputable.",
  },
  {
    table: "opportunity_merges",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Duplicate-merge bookkeeping.",
  },
  {
    table: "opportunity_views",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Per-user read tracking.",
  },
  {
    table: "payment_reminder_generation_claims",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Cron claim rows.",
  },
  {
    table: "payment_review_writeoff_receipts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Receipts for the write-off action; the write-off itself is on the payment.",
  },
  {
    table: "payments",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "phase_c_category_auto_send_acceptances",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Auto-send acceptance bookkeeping.",
  },
  {
    table: "pipeline_stage_configs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "portal_branding",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "portal_messages",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "portal_tokens",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Client-portal access tokens; must never leave the system in an export.",
  },
  {
    table: "product_bundle_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "product_material_quantity_rules",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "products",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_material_demands",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_material_snapshot_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "project_material_snapshots",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "project_note_mention_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Mention notification bookkeeping.",
  },
  {
    table: "project_notes",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_photo_annotations",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_photos",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_status_lifecycle_outbox",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Status-change notification outbox.",
  },
  {
    table: "project_tasks",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "project_views",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Per-user read tracking.",
  },
  {
    table: "projects",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "qbo_customer_matches",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks customer match cache.",
  },
  {
    table: "qbo_estimate_opportunity_links",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: false,
    reason:
      "QuickBooks link bookkeeping.",
  },
  {
    table: "qbo_import_runs",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import run log.",
  },
  {
    table: "qbo_item_product_mappings",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: false,
    reason:
      "QuickBooks item mapping bookkeeping.",
  },
  {
    table: "qbo_staging_customers",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import staging.",
  },
  {
    table: "qbo_staging_estimates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import staging.",
  },
  {
    table: "qbo_staging_invoices",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import staging.",
  },
  {
    table: "qbo_staging_line_items",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import staging.",
  },
  {
    table: "qbo_staging_payments",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "QuickBooks import staging.",
  },
  {
    table: "recurring_expenses",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "roles",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "site_visit_artifacts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "site_visit_checklist_answers",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "site_visit_identity_drafts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "site_visits",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "spec_module_entitlements",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "retain",
    export: false,
    reason:
      "Part of the OPS SPEC sales ledger, not the customer's operating data; retained with the rest of that ledger.",
  },
  {
    table: "stage_transitions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "sub_clients",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_material_allocations",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_material_consumption_requests",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Idempotency records for stock consumption.",
  },
  {
    table: "task_mutation_events",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Task mutation event log.",
  },
  {
    table: "task_recurrences",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_reminders",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_templates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "text",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_type_reminders",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "task_types",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "tax_rates",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "team_invitations",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Pending invite tokens.",
  },
  {
    table: "trial_attributions",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "OPS marketing attribution, not customer data.",
  },
  {
    table: "trial_expiry_notifications",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Trial notification bookkeeping.",
  },
  {
    table: "unanswered_lead_local_draft_generation_claims",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Cron claim rows.",
  },
  {
    table: "unanswered_lead_message_projections",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Derived projections, recomputable.",
  },
  {
    table: "user_dashboard_preferences",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "user_email_aliases",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "user_permission_overrides",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: true,
  },
  {
    table: "users",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
  {
    table: "user_permission_change_deliveries",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Permission-change notification delivery receipts. Purged after permission overrides and user tombstones because those authority mutations enqueue fresh delivery rows.",
  },
  {
    table: "weather_forecasts",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Cached third-party weather data.",
  },
  {
    table: "wizard_analytics",
    scope: "company",
    companyColumn: "company_id",
    companyColumnType: "uuid",
    softDeletable: false,
    deleteStrategy: "hard",
    export: false,
    reason:
      "Wizard telemetry, not customer data.",
  },
  {
    table: "companies",
    scope: "company",
    companyColumn: "id",
    companyColumnType: "uuid",
    softDeletable: true,
    deleteStrategy: "soft",
    export: true,
  },
];

export const UNTYPED_TABLE_ALLOWLIST: readonly string[] = [];

export const OUT_OF_SCOPE_TABLES: readonly OutOfScopeEntry[] = [
  {
    table: "certificates",
    reason:
      "ops-learn course certificate. Its user reference points at auth.users, not public.users, and those id spaces are disjoint under the Firebase bridge (0 of 211 public.users rows exist in auth.users, verified against prod 2026-07-29) — so no company can be joined to these rows at all. Its other parent, courses, is a global ops-learn catalog with no tenant column. ops-learn is a separate product with its own account lifecycle and owns deletion of learner records.",
  },
  {
    table: "streaks",
    reason:
      "ops-learn activity streak, keyed to an auth.users identity rather than public.users — the same disjoint id spaces as certificates, so it is unreachable from a company. Owned by ops-learn's account lifecycle, not by this cascade.",
  },
  {
    table: "email_pause_audit_log",
    reason:
      "Global OPS email kill-switch audit trail — who paused platform-wide sending and why. It reaches a user only through actor_user_id, and into auth.users at that: authorship, not ownership. Not scoped to any tenant, and an audit trail of a platform-level control must not be deleted with one customer.",
  },
  {
    table: "email_pause_state",
    reason:
      "Global OPS email kill-switch state, keyed by scope rather than by tenant — a single platform-wide row. paused_by / resumed_by are actor references into auth.users, i.e. authorship, not ownership.",
  },
  {
    table: "email_template_versions",
    reason:
      "Global OPS transactional-email template version ledger, shared across every tenant. created_by_user_id is an authorship reference into auth.users; the templates are OPS's own, not a customer's data.",
  },
];

/**
 * Every classified table. Parent-scoped children come first because the
 * deletion cascade must clear them before their parents disappear.
 */
export const COMPANY_DATA_MANIFEST: readonly ManifestEntry[] = [
  ...PARENT_SCOPED_DATA,
  ...COMPANY_SCOPED_DATA,
];

let indexCache: Map<string, ManifestEntry> | null = null;

/** Table name → entry. */
export function manifestByTable(): Map<string, ManifestEntry> {
  if (!indexCache) {
    indexCache = new Map(COMPANY_DATA_MANIFEST.map((e) => [e.table, e]));
  }
  return indexCache;
}

/**
 * The ordered deletion sequence: parent-scoped children, then company-scoped
 * tables by foreign-key depth, then the company row. Retained tables are
 * excluded — they are deliberately left alone.
 */
export function deletionPlan(): ManifestEntry[] {
  return COMPANY_DATA_MANIFEST.filter((e) => e.deleteStrategy !== "retain");
}

/** Serializable plan passed verbatim to the transactional purge function. */
export function transactionalPurgePlan(): TransactionalPurgePlan {
  return {
    manifest_version: MANIFEST_VERSION,
    cycle_breakers: FK_CYCLE_BREAKERS,
    steps: deletionPlan().map((entry) => ({
      ...entry,
      definer_purged: isDefinerPurged(entry.table),
    })),
  };
}

/** Everything the customer is entitled to take with them. */
export function exportPlan(): ManifestEntry[] {
  return COMPANY_DATA_MANIFEST.filter((e) => e.export);
}

/** Split `ids` into `in.()`-sized chunks. */
export function chunkIds(ids: readonly string[]): string[][] {
  const chunks: string[][] = [];
  for (let i = 0; i < ids.length; i += ID_CHUNK_SIZE) {
    chunks.push(ids.slice(i, i + ID_CHUNK_SIZE) as string[]);
  }
  return chunks;
}
