/**
 * Integration test — auto-draft mailbox push (T3)
 *
 * Tests `maybeAutoGenerateDraft` (exported for testing) directly.
 * This function is called fire-and-forget from the sync loop, so testing it
 * in isolation is both cleaner and more reliable than driving through the full
 * SyncEngine.runSync path (which requires a complete Supabase double for the
 * entire 12-step sync cycle).
 *
 * External boundaries mocked:
 *   - AdminFeatureOverrideService
 *   - WritingProfileService
 *   - AIDraftService
 *   - AutoSendService
 *   - EmailService (provider access)
 *   - requireSupabase / setSupabaseOverride (DB calls)
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { setSupabaseOverride } from "@/lib/supabase/helpers";
import type { NormalizedEmail } from "@/lib/api/services/email-provider";
import type { EmailConnection } from "@/lib/types/email-connection";

// ─── Hoisted mocks ────────────────────────────────────────────────────────────

const {
  isAIFeatureEnabledMock,
  getProfileMock,
  getConfidenceMock,
  generateDraftMock,
  isEnabledAutoSendMock,
  getProviderMock,
} = vi.hoisted(() => ({
  isAIFeatureEnabledMock: vi.fn(),
  getProfileMock: vi.fn(),
  getConfidenceMock: vi.fn(),
  generateDraftMock: vi.fn(),
  isEnabledAutoSendMock: vi.fn(),
  getProviderMock: vi.fn(),
}));

vi.mock("@/lib/api/services/admin-feature-override-service", () => ({
  AdminFeatureOverrideService: {
    isAIFeatureEnabled: isAIFeatureEnabledMock,
    isFeatureEnabled: vi.fn().mockResolvedValue(false),
  },
}));

vi.mock("@/lib/api/services/writing-profile-service", () => ({
  WritingProfileService: {
    getProfile: getProfileMock,
    getConfidence: getConfidenceMock,
  },
}));

vi.mock("@/lib/api/services/ai-draft-service", () => ({
  AIDraftService: {
    generateDraft: generateDraftMock,
  },
}));

vi.mock("@/lib/api/services/auto-send-service", () => ({
  AutoSendService: {
    isEnabled: isEnabledAutoSendMock,
    scheduleAutoSend: vi.fn(),
  },
}));

vi.mock("@/lib/api/services/email-service", () => ({
  EmailService: {
    getProvider: getProviderMock,
    getConnection: vi.fn(),
    updateConnection: vi.fn(),
  },
}));

// Import AFTER mocks are registered
import { maybeAutoGenerateDraft } from "@/lib/api/services/sync-engine";

// ─── In-memory Supabase double ────────────────────────────────────────────────

interface DbState {
  aiDraftHistory: Array<Record<string, unknown>>;
  emailConnections: Array<Record<string, unknown>>;
  notifications: Array<Record<string, unknown>>;
}

function makeSupabaseDouble(state: DbState) {
  class Query {
    private _table: string;
    private _action: "select" | "insert" | "update" = "select";
    private _payload: Record<string, unknown> | null = null;
    private _filters = new Map<string, unknown>();

    constructor(table: string) {
      this._table = table;
    }

    select(_cols?: string) { return this; }

    eq(col: string, val: unknown) {
      this._filters.set(col, val);
      return this;
    }

    insert(payload: Record<string, unknown>) {
      this._action = "insert";
      this._payload = payload;
      if (this._table === "notifications") {
        state.notifications.push(payload);
      }
      return this;
    }

    update(payload: Record<string, unknown>) {
      this._action = "update";
      this._payload = payload;
      return this;
    }

    private _resolve(): { data: unknown; error: null } {
      if (this._table === "email_connections" && this._action === "select") {
        const id = this._filters.get("id");
        const companyId = this._filters.get("company_id");
        const row =
          state.emailConnections.find(
            (c) => c.id === id && (!companyId || c.company_id === companyId)
          ) ?? null;
        return { data: row, error: null };
      }
      if (this._table === "ai_draft_history" && this._action === "select") {
        const connId = this._filters.get("connection_id");
        const threadId = this._filters.get("thread_id");
        const rows = state.aiDraftHistory.filter(
          (r) => r.connection_id === connId && r.thread_id === threadId
        );
        return { data: rows, error: null };
      }
      if (this._table === "ai_draft_history" && this._action === "update") {
        // Filters are all set by the time _resolve() runs — apply the mutation now.
        const id = this._filters.get("id");
        const row = state.aiDraftHistory.find((r) => r.id === id);
        if (row && this._payload) Object.assign(row, this._payload);
        return { data: null, error: null };
      }
      if (this._action === "insert" || this._action === "update") {
        return { data: null, error: null };
      }
      return { data: null, error: null };
    }

    then<T1 = unknown, T2 = never>(
      onFulfilled?: ((val: unknown) => T1 | PromiseLike<T1>) | null,
      onRejected?: ((reason: unknown) => T2 | PromiseLike<T2>) | null
    ) {
      return Promise.resolve(this._resolve()).then(onFulfilled, onRejected);
    }

    async single() {
      return this._resolve() as { data: Record<string, unknown> | null; error: null };
    }
  }

  return {
    from: (table: string) => new Query(table),
  };
}

// ─── Fixtures ─────────────────────────────────────────────────────────────────

function makeConnection(overrides: Partial<EmailConnection> = {}): EmailConnection {
  return {
    id: "conn-1",
    companyId: "company-1",
    provider: "gmail",
    type: "company",
    userId: "user-1",
    email: "ops@example.com",
    accessToken: "token",
    refreshToken: "refresh",
    expiresAt: new Date("2099-01-01"),
    historyId: "sync-token",
    syncEnabled: true,
    lastSyncedAt: null,
    syncIntervalMinutes: 15,
    syncFilters: {
      includeSentMail: false,
      estimateSubjectPatterns: ["estimate"],
      companyDomains: ["example.com"],
      teamForwarders: [],
    },
    webhookSubscriptionId: null,
    webhookExpiresAt: null,
    opsLabelId: null,
    aiReviewEnabled: false,
    aiMemoryEnabled: false,
    status: "active",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
    ...overrides,
  };
}

function makeInboundEmail(overrides: Partial<NormalizedEmail> = {}): NormalizedEmail {
  return {
    id: "msg-1",
    threadId: "thread-1",
    from: "Client Person <client@customer.com>",
    fromName: "Client Person",
    to: ["ops@example.com"],
    cc: [],
    subject: "Need a quote",
    snippet: "Please send a quote.",
    bodyText: "Please send a quote for the deck repair.",
    date: new Date("2026-06-01T10:00:00Z"),
    labelIds: ["INBOX"],
    isRead: false,
    hasAttachments: false,
    sizeEstimate: 800,
    ...overrides,
  };
}

/** auto_send_settings that qualify for auto_draft (not auto_send) */
const DRAFT_SETTINGS = {
  auto_draft_enabled: true,
  auto_send_enabled: false,
  category_autonomy: {
    // "client_quoting" covers subjects containing "quote"/"estimate"/"pricing"
    client_quoting: "auto_draft",
    // "general" is the fallback for unclassified subjects
    general: "auto_draft",
  },
};

// ─── Setup / teardown ─────────────────────────────────────────────────────────

beforeEach(() => {
  vi.clearAllMocks();
  isAIFeatureEnabledMock.mockResolvedValue(true);
  getProfileMock.mockResolvedValue({ emails_analyzed: 100 });
  getConfidenceMock.mockReturnValue(0.9); // above 0.75 threshold
  generateDraftMock.mockResolvedValue({
    available: true,
    draft: "Thank you for reaching out. I will send you a quote shortly.",
    draftHistoryId: "draft-history-1",
  });
  isEnabledAutoSendMock.mockResolvedValue({ enabled: false, settings: null });
});

afterEach(() => {
  setSupabaseOverride(null);
});

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("maybeAutoGenerateDraft — mailbox push (T3)", () => {
  it("calls provider.createDraft with Re: subject + threadId and updates ai_draft_history with mailbox_draft_id", async () => {
    const state: DbState = {
      aiDraftHistory: [
        {
          id: "draft-history-1",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    const createDraftMock = vi.fn().mockResolvedValue("provider-draft-id-1");
    const updateDraftMock = vi.fn().mockResolvedValue(undefined);
    getProviderMock.mockReturnValue({
      createDraft: createDraftMock,
      updateDraft: updateDraftMock,
    });

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(
      makeInboundEmail(),
      makeConnection(),
      "opp-1"
    );

    // provider.createDraft must have been called — no prior mailbox draft
    expect(createDraftMock).toHaveBeenCalledTimes(1);
    expect(createDraftMock).toHaveBeenCalledWith(
      "client@customer.com",  // extractSenderEmail(email.from)
      "Re: Need a quote",     // Re: prefix added
      expect.stringContaining("Thank you"),  // draft body
      "thread-1"              // threadId
    );
    expect(updateDraftMock).not.toHaveBeenCalled();

    // ai_draft_history row must carry both status and mailbox_draft_id
    const row = state.aiDraftHistory.find((r) => r.id === "draft-history-1");
    expect(row?.status).toBe("auto_drafted");
    expect(row?.mailbox_draft_id).toBe("provider-draft-id-1");
  });

  it("does not add a Re: prefix when the subject already starts with Re:", async () => {
    const state: DbState = {
      aiDraftHistory: [
        {
          id: "draft-history-1",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    const createDraftMock = vi.fn().mockResolvedValue("draft-id-reply");
    getProviderMock.mockReturnValue({
      createDraft: createDraftMock,
      updateDraft: vi.fn(),
    });

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(
      makeInboundEmail({ subject: "Re: Need a quote" }),
      makeConnection(),
      "opp-1"
    );

    expect(createDraftMock).toHaveBeenCalledWith(
      "client@customer.com",
      "Re: Need a quote",   // not "Re: Re: Need a quote"
      expect.any(String),
      "thread-1"
    );
  });

  it("treats a lowercase re: subject as already-replied (no double prefix)", async () => {
    const state: DbState = {
      aiDraftHistory: [
        {
          id: "draft-history-1",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        { id: "conn-1", company_id: "company-1", auto_send_settings: DRAFT_SETTINGS },
      ],
      notifications: [],
    };

    const createDraftMock = vi.fn().mockResolvedValue("draft-id-lc");
    getProviderMock.mockReturnValue({
      createDraft: createDraftMock,
      updateDraft: vi.fn(),
    });
    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(
      makeInboundEmail({ subject: "re: Need a quote" }),
      makeConnection(),
      "opp-1"
    );

    expect(createDraftMock).toHaveBeenCalledWith(
      "client@customer.com",
      "re: Need a quote", // kept as-is; case-insensitive match, no double prefix
      expect.any(String),
      "thread-1"
    );
  });

  it("calls provider.updateDraft instead of createDraft when a prior unresolved mailbox draft exists (idempotency)", async () => {
    const state: DbState = {
      aiDraftHistory: [
        // Existing row with mailbox_draft_id and status auto_drafted
        {
          id: "draft-history-prior",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "auto_drafted",
          mailbox_draft_id: "existing-provider-draft",
        },
        // New row returned by generateDraft
        {
          id: "draft-history-2",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    generateDraftMock.mockResolvedValue({
      available: true,
      draft: "Updated draft body.",
      draftHistoryId: "draft-history-2",
    });

    const createDraftMock = vi.fn().mockResolvedValue("new-provider-draft");
    const updateDraftMock = vi.fn().mockResolvedValue(undefined);
    getProviderMock.mockReturnValue({
      createDraft: createDraftMock,
      updateDraft: updateDraftMock,
    });

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(
      makeInboundEmail(),
      makeConnection(),
      "opp-1"
    );

    // Must reuse existing draft via updateDraft, not create a second one
    expect(updateDraftMock).toHaveBeenCalledTimes(1);
    expect(updateDraftMock).toHaveBeenCalledWith(
      "existing-provider-draft",
      "client@customer.com",
      "Re: Need a quote",
      "Updated draft body.",
      "thread-1"
    );
    expect(createDraftMock).not.toHaveBeenCalled();

    // New row should carry existing mailbox_draft_id (updateDraft returns void)
    const newRow = state.aiDraftHistory.find((r) => r.id === "draft-history-2");
    expect(newRow?.status).toBe("auto_drafted");
    expect(newRow?.mailbox_draft_id).toBe("existing-provider-draft");
  });

  it("does not throw out of maybeAutoGenerateDraft when provider.createDraft fails (non-fatal)", async () => {
    const state: DbState = {
      aiDraftHistory: [
        {
          id: "draft-history-1",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    const createDraftMock = vi.fn().mockRejectedValue(new Error("Network timeout"));
    getProviderMock.mockReturnValue({
      createDraft: createDraftMock,
      updateDraft: vi.fn(),
    });

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    // Must not throw — the provider failure is caught inside and logged
    await expect(
      maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1")
    ).resolves.toBeUndefined();

    // Draft creation was attempted
    expect(createDraftMock).toHaveBeenCalledTimes(1);

    // Status-only fallback update still happens so the UI shows the AI draft
    const row = state.aiDraftHistory.find((r) => r.id === "draft-history-1");
    expect(row?.status).toBe("auto_drafted");
    // mailbox_draft_id stays null since the push failed
    expect(row?.mailbox_draft_id).toBeNull();
  });
});
