/**
 * Integration test — inbox notification gating (T11)
 *
 * Verifies three behaviors introduced by the dark-launch gating layer:
 *
 *   1. AUTO_DRAFT_READY: only inserted when inbox_ui is ENABLED.
 *   2. One-time explainer ("Replies, pre-drafted"): inserted exactly once on
 *      the first successful mailbox-draft placement when inbox_ui is DISABLED.
 *      Not inserted again on subsequent placements.
 *   3. EMAIL_SYNC_COMPLETE: action_url is /pipeline when inbox_ui is OFF,
 *      /inbox when ON.
 *
 * External boundaries mocked (same set as auto-draft-mailbox.test.ts):
 *   - AdminFeatureOverrideService (both isAIFeatureEnabled + isFeatureEnabled)
 *   - WritingProfileService
 *   - AIDraftService
 *   - AutoSendService
 *   - EmailService
 *   - requireSupabase / setSupabaseOverride
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { setSupabaseOverride } from "@/lib/supabase/helpers";
import type { NormalizedEmail } from "@/lib/api/services/email-provider";
import type { EmailConnection } from "@/lib/types/email-connection";

// ─── Hoisted mocks ────────────────────────────────────────────────────────────

const {
  isAIFeatureEnabledMock,
  isFeatureEnabledMock,
  getProfileMock,
  getConfidenceMock,
  generateDraftMock,
  isEnabledAutoSendMock,
  getProviderMock,
} = vi.hoisted(() => ({
  isAIFeatureEnabledMock: vi.fn(),
  isFeatureEnabledMock: vi.fn(),
  getProfileMock: vi.fn(),
  getConfidenceMock: vi.fn(),
  generateDraftMock: vi.fn(),
  isEnabledAutoSendMock: vi.fn(),
  getProviderMock: vi.fn(),
}));

vi.mock("@/lib/api/services/admin-feature-override-service", () => ({
  AdminFeatureOverrideService: {
    isAIFeatureEnabled: isAIFeatureEnabledMock,
    isFeatureEnabled: isFeatureEnabledMock,
  },
}));

vi.mock("@/lib/api/services/writing-profile-service", () => ({
  WritingProfileService: {
    getProfile: getProfileMock,
    getConfidence: getConfidenceMock,
  },
}));

vi.mock("@/lib/api/services/ai-draft-service", () => ({
  AIDraftService: {
    generateDraft: generateDraftMock,
  },
}));

vi.mock("@/lib/api/services/auto-send-service", () => ({
  AutoSendService: {
    isEnabled: isEnabledAutoSendMock,
    scheduleAutoSend: vi.fn(),
  },
}));

vi.mock("@/lib/api/services/email-service", () => ({
  EmailService: {
    getProvider: getProviderMock,
    getConnection: vi.fn(),
    updateConnection: vi.fn(),
  },
}));

// Import AFTER mocks are registered
import { maybeAutoGenerateDraft } from "@/lib/api/services/sync-engine";

// ─── In-memory Supabase double ────────────────────────────────────────────────

interface DbState {
  aiDraftHistory: Array<Record<string, unknown>>;
  emailConnections: Array<Record<string, unknown>>;
  notifications: Array<Record<string, unknown>>;
}

/**
 * Extended double that handles the additional query patterns needed by T11:
 *   - .not(col, "is", null) — filter rows where col IS NOT NULL
 *   - .limit(n) — return at most n rows
 *
 * Existing patterns from auto-draft-mailbox.test.ts are preserved.
 */
function makeSupabaseDouble(state: DbState) {
  class Query {
    private _table: string;
    private _action: "select" | "insert" | "update" = "select";
    private _payload: Record<string, unknown> | null = null;
    private _filters = new Map<string, unknown>();
    private _notNullCols: string[] = [];
    private _limitN: number | null = null;

    constructor(table: string) {
      this._table = table;
    }

    select(_cols?: string) { return this; }

    eq(col: string, val: unknown) {
      this._filters.set(col, val);
      return this;
    }

    not(col: string, _op: string, _val: unknown) {
      // Only "is null" / "is not null" patterns are used here.
      // Record the column as a "must not be null" filter.
      this._notNullCols.push(col);
      return this;
    }

    limit(n: number) {
      this._limitN = n;
      return this;
    }

    insert(payload: Record<string, unknown>) {
      this._action = "insert";
      this._payload = payload;
      if (this._table === "notifications") {
        state.notifications.push(payload);
      }
      return this;
    }

    update(payload: Record<string, unknown>) {
      this._action = "update";
      this._payload = payload;
      return this;
    }

    private _resolve(): { data: unknown; error: null } {
      if (this._table === "email_connections" && this._action === "select") {
        const id = this._filters.get("id");
        const companyId = this._filters.get("company_id");
        const row =
          state.emailConnections.find(
            (c) => c.id === id && (!companyId || c.company_id === companyId)
          ) ?? null;
        return { data: row, error: null };
      }
      if (this._table === "ai_draft_history" && this._action === "select") {
        const connId = this._filters.get("connection_id");
        const threadId = this._filters.get("thread_id");

        let rows = state.aiDraftHistory.filter((r) => {
          if (connId !== undefined && r.connection_id !== connId) return false;
          if (threadId !== undefined && r.thread_id !== threadId) return false;
          // Apply .not("col", "is", null) — keep only rows where col is not null
          for (const col of this._notNullCols) {
            if (r[col] === null || r[col] === undefined) return false;
          }
          return true;
        });

        if (this._limitN !== null) {
          rows = rows.slice(0, this._limitN);
        }

        return { data: rows, error: null };
      }
      if (this._table === "ai_draft_history" && this._action === "update") {
        const id = this._filters.get("id");
        const row = state.aiDraftHistory.find((r) => r.id === id);
        if (row && this._payload) Object.assign(row, this._payload);
        return { data: null, error: null };
      }
      if (this._action === "insert" || this._action === "update") {
        return { data: null, error: null };
      }
      return { data: null, error: null };
    }

    then<T1 = unknown, T2 = never>(
      onFulfilled?: ((val: unknown) => T1 | PromiseLike<T1>) | null,
      onRejected?: ((reason: unknown) => T2 | PromiseLike<T2>) | null
    ) {
      return Promise.resolve(this._resolve()).then(onFulfilled, onRejected);
    }

    async single() {
      return this._resolve() as { data: Record<string, unknown> | null; error: null };
    }
  }

  return {
    from: (table: string) => new Query(table),
  };
}

// ─── Fixtures ─────────────────────────────────────────────────────────────────

function makeConnection(overrides: Partial<EmailConnection> = {}): EmailConnection {
  return {
    id: "conn-1",
    companyId: "company-1",
    provider: "gmail",
    type: "company",
    userId: "user-1",
    email: "ops@example.com",
    accessToken: "token",
    refreshToken: "refresh",
    expiresAt: new Date("2099-01-01"),
    historyId: "sync-token",
    syncEnabled: true,
    lastSyncedAt: null,
    syncIntervalMinutes: 15,
    syncFilters: {
      includeSentMail: false,
      estimateSubjectPatterns: ["estimate"],
      companyDomains: ["example.com"],
      teamForwarders: [],
    },
    webhookSubscriptionId: null,
    webhookExpiresAt: null,
    opsLabelId: null,
    aiReviewEnabled: false,
    aiMemoryEnabled: false,
    status: "active",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
    ...overrides,
  };
}

function makeInboundEmail(overrides: Partial<NormalizedEmail> = {}): NormalizedEmail {
  return {
    id: "msg-1",
    threadId: "thread-1",
    from: "Client Person <client@customer.com>",
    fromName: "Client Person",
    to: ["ops@example.com"],
    cc: [],
    subject: "Need a quote",
    snippet: "Please send a quote.",
    bodyText: "Please send a quote for the deck repair.",
    date: new Date("2026-06-01T10:00:00Z"),
    labelIds: ["INBOX"],
    isRead: false,
    hasAttachments: false,
    sizeEstimate: 800,
    ...overrides,
  };
}

/** auto_send_settings that qualify for auto_draft (not auto_send) */
const DRAFT_SETTINGS = {
  auto_draft_enabled: true,
  auto_send_enabled: false,
  category_autonomy: {
    client_quoting: "auto_draft",
    general: "auto_draft",
  },
};

/** Base state shared across most tests */
function makeBaseState(): DbState {
  return {
    aiDraftHistory: [
      {
        id: "draft-history-1",
        connection_id: "conn-1",
        thread_id: "thread-1",
        status: "pending",
        mailbox_draft_id: null,
      },
    ],
    emailConnections: [
      {
        id: "conn-1",
        company_id: "company-1",
        auto_send_settings: DRAFT_SETTINGS,
      },
    ],
    notifications: [],
  };
}

// ─── Setup / teardown ─────────────────────────────────────────────────────────

beforeEach(() => {
  vi.clearAllMocks();
  // All checks pass by default
  isAIFeatureEnabledMock.mockResolvedValue(true);
  // inbox_ui defaults to OFF (dark-launch default)
  isFeatureEnabledMock.mockResolvedValue(false);
  getProfileMock.mockResolvedValue({ emails_analyzed: 100 });
  getConfidenceMock.mockReturnValue(0.9);
  generateDraftMock.mockResolvedValue({
    available: true,
    draft: "Thank you for reaching out. I will send you a quote shortly.",
    draftHistoryId: "draft-history-1",
  });
  isEnabledAutoSendMock.mockResolvedValue({ enabled: false, settings: null });
});

afterEach(() => {
  setSupabaseOverride(null);
});

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("T11 — AUTO_DRAFT_READY notification gating", () => {
  it("does NOT insert AUTO_DRAFT_READY notification when inbox_ui is OFF", async () => {
    const state = makeBaseState();

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("provider-draft-id"),
      updateDraft: vi.fn(),
    });

    isFeatureEnabledMock.mockResolvedValue(false); // inbox hidden

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const draftReadyNotifs = state.notifications.filter(
      (n) => n.title === "Draft ready"
    );
    expect(draftReadyNotifs).toHaveLength(0);
  });

  it("inserts AUTO_DRAFT_READY notification when inbox_ui is ON", async () => {
    const state = makeBaseState();

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("provider-draft-id"),
      updateDraft: vi.fn(),
    });

    isFeatureEnabledMock.mockResolvedValue(true); // inbox visible

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const draftReadyNotifs = state.notifications.filter(
      (n) => n.title === "Draft ready"
    );
    expect(draftReadyNotifs).toHaveLength(1);
    expect(draftReadyNotifs[0].action_url).toBe("/inbox");
    expect(draftReadyNotifs[0].type).toBe("ai_milestone");
  });
});

describe("T11 — one-time draft explainer notification", () => {
  it("inserts explainer on first mailbox draft when inbox_ui is OFF", async () => {
    const state = makeBaseState();
    // No prior rows with mailbox_draft_id — this is the first placement

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("provider-draft-id"),
      updateDraft: vi.fn(),
    });

    isFeatureEnabledMock.mockResolvedValue(false); // inbox hidden

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const explainerNotifs = state.notifications.filter(
      (n) => n.title === "Replies, pre-drafted"
    );
    expect(explainerNotifs).toHaveLength(1);
    expect(explainerNotifs[0]).toMatchObject({
      user_id: "user-1",
      company_id: "company-1",
      type: "ai_milestone",
      persistent: false,
      action_url: "/settings?tab=integrations",
      action_label: "Email settings",
    });
  });

  it("does NOT insert explainer on second mailbox draft (dedup)", async () => {
    const state: DbState = {
      aiDraftHistory: [
        // Prior successful mailbox draft exists for this connection
        {
          id: "draft-history-prior",
          connection_id: "conn-1",
          thread_id: "thread-prior",
          status: "auto_drafted",
          mailbox_draft_id: "existing-provider-draft",
        },
        // New history row for current draft
        {
          id: "draft-history-2",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    generateDraftMock.mockResolvedValue({
      available: true,
      draft: "Second draft.",
      draftHistoryId: "draft-history-2",
    });

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("new-provider-draft"),
      updateDraft: vi.fn(),
    });

    isFeatureEnabledMock.mockResolvedValue(false); // inbox hidden

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const explainerNotifs = state.notifications.filter(
      (n) => n.title === "Replies, pre-drafted"
    );
    expect(explainerNotifs).toHaveLength(0);
  });

  it("does NOT insert explainer when inbox_ui is ON", async () => {
    const state = makeBaseState();

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("provider-draft-id"),
      updateDraft: vi.fn(),
    });

    isFeatureEnabledMock.mockResolvedValue(true); // inbox visible

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const explainerNotifs = state.notifications.filter(
      (n) => n.title === "Replies, pre-drafted"
    );
    expect(explainerNotifs).toHaveLength(0);
  });

  it("does NOT insert explainer when the mailbox path is updateDraft (existing draft reused)", async () => {
    // When an existing mailbox draft is reused via updateDraft, we don't fire
    // the explainer — the user already received it on the createDraft call.
    const state: DbState = {
      aiDraftHistory: [
        {
          id: "draft-history-prior",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "auto_drafted",
          mailbox_draft_id: "existing-provider-draft",
        },
        {
          id: "draft-history-1",
          connection_id: "conn-1",
          thread_id: "thread-1",
          status: "pending",
          mailbox_draft_id: null,
        },
      ],
      emailConnections: [
        {
          id: "conn-1",
          company_id: "company-1",
          auto_send_settings: DRAFT_SETTINGS,
        },
      ],
      notifications: [],
    };

    getProviderMock.mockReturnValue({
      createDraft: vi.fn().mockResolvedValue("new-draft"),
      updateDraft: vi.fn().mockResolvedValue(undefined),
    });

    isFeatureEnabledMock.mockResolvedValue(false); // inbox hidden

    setSupabaseOverride(makeSupabaseDouble(state) as never);

    await maybeAutoGenerateDraft(makeInboundEmail(), makeConnection(), "opp-1");

    const explainerNotifs = state.notifications.filter(
      (n) => n.title === "Replies, pre-drafted"
    );
    // updateDraft path: explainer not triggered (only fires from createDraft branch)
    expect(explainerNotifs).toHaveLength(0);
  });
});
