-- Weekly journal: generated header photographs.
--
-- Every weekly post carries a photograph generated by OPS from the writer's
-- art direction (package.article.image_prompt). The first image is made when
-- a draft is promoted; after that the operator can ask for a new one, and a
-- published post can have its photograph replaced for eight days. Requests are
-- durable, so a failed generation retries on the next hourly tick and gives up
-- after three failures with a rail item. Generations per slot are capped so a
-- loop can never run up the image bill.
--
-- Additive: four columns, two replaced functions with unchanged signatures,
-- three new functions. Nothing existing is removed.

alter table public.journal_editorial_assignments
 add column image_generations integer not null default 0 check (image_generations between 0 and 8),
 add column image_requested_at timestamptz,
 add column image_requested_by text check (image_requested_by is null or length(image_requested_by) <= 200),
 add column image_failures integer not null default 0 check (image_failures between 0 and 3);

-- The first photograph is made at promotion, so scheduling counts it.
create or replace function public.schedule_journal_editorial_assignment(p_id uuid, p_preview jsonb, p_publish_at timestamptz)
returns text language plpgsql security invoker set search_path = '' as $$
declare final_state text;
begin
 if p_preview is null or p_publish_at is null then raise exception 'Schedule requires a preview and a launch time'; end if;
 update public.journal_editorial_assignments set
  state = 'scheduled', preview = p_preview, publish_at = p_publish_at,
  image_generations = least(image_generations + 1, 8), image_failures = 0,
  scheduled_at = now(), updated_at = now()
 where id = p_id and state = 'drafted'
 returning state into final_state;
 return final_state;
end $$;

-- Unchanged guards; the live row now also keeps the art direction that made
-- its photograph, alongside the photograph itself.
create or replace function public.publish_journal_editorial_assignment(p_id uuid, p_manual boolean, p_actor text)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
 s public.journal_editorial_settings;
 a public.journal_editorial_assignments;
 v_article jsonb;
 v_blog uuid;
 v_override boolean;
begin
 select * into strict s from public.journal_editorial_settings where id for update;
 select * into a from public.journal_editorial_assignments where id = p_id for update;
 if not found then return jsonb_build_object('code', 'NOT_FOUND'); end if;
 if a.state = 'published' then
  return jsonb_build_object('state', 'published', 'blog_id', a.blog_id, 'replay', true);
 end if;
 v_override := coalesce(p_manual, false) and a.state = 'blocked' and a.last_code = 'WEEKLY_ALREADY_LIVE';
 if a.state <> 'scheduled' and not v_override then
  return jsonb_build_object('code', 'NOT_SCHEDULED', 'state', a.state);
 end if;
 if not coalesce(p_manual, false) then
  if s.mode <> 'publish' or a.mode is distinct from 'publish' then return jsonb_build_object('code', 'HELD'); end if;
  if a.publish_at > now() then return jsonb_build_object('code', 'NOT_DUE'); end if;
 end if;
 if a.package is null or a.slug is null or a.preview is null then
  update public.journal_editorial_assignments set state = 'blocked', last_code = 'PACKAGE_MISSING', blocked_at = now(), updated_at = now() where id = p_id;
  return jsonb_build_object('code', 'PACKAGE_MISSING');
 end if;
 if a.drafted_at < now() - interval '8 days' then
  update public.journal_editorial_assignments set state = 'blocked', last_code = 'STALE_DRAFT', blocked_at = now(), updated_at = now() where id = p_id;
  return jsonb_build_object('code', 'STALE_DRAFT');
 end if;
 if exists (select 1 from public.blog_posts b where b.slug = a.slug) then
  update public.journal_editorial_assignments set state = 'blocked', last_code = 'SLUG_TAKEN', blocked_at = now(), updated_at = now() where id = p_id;
  return jsonb_build_object('code', 'SLUG_TAKEN');
 end if;
 if not v_override and exists (
  select 1 from public.blog_posts b
  where b.source = 'weekly' and b.is_live and b.published_at > now() - interval '5 days'
 ) then
  update public.journal_editorial_assignments set state = 'blocked', last_code = 'WEEKLY_ALREADY_LIVE', blocked_at = now(), updated_at = now() where id = p_id;
  return jsonb_build_object('code', 'WEEKLY_ALREADY_LIVE');
 end if;
 v_article := a.package->'article';
 insert into public.blog_posts (
  title, subtitle, slug, author, content, summary, teaser, meta_title, thumbnail_url, image_prompt,
  category_id, is_live, word_count, faqs, published_at, email_content, source
 ) values (
  v_article->>'title', v_article->>'subtitle', a.slug, s.byline, a.package->>'html',
  v_article->>'summary', v_article->>'teaser', v_article->>'meta_title', a.preview->>'url',
  nullif(v_article->>'image_prompt', ''),
  (a.package->>'category_id')::uuid, true, (a.package->>'word_count')::integer,
  coalesce(v_article->'faqs', '[]'::jsonb), now(), v_article->>'email_content', 'weekly'
 ) returning id into v_blog;
 -- A backlog topic is spent when its post goes live, not when it is drafted:
 -- a stopped draft leaves the idea available for another week.
 if coalesce(v_article->'topic'->>'backlog_topic_id', '') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
  update public.blog_topics set used = true, updated_at = now()
  where id = (v_article->'topic'->>'backlog_topic_id')::uuid;
 end if;
 update public.journal_editorial_assignments set
  state = 'published', blog_id = v_blog, published_at = now(), last_code = null,
  attempt_log = case when jsonb_array_length(attempt_log) < 40 then attempt_log || jsonb_build_array(jsonb_build_object(
   'event', 'published', 'manual', coalesce(p_manual, false), 'actor', left(coalesce(p_actor, ''), 200), 'at', now()))
   else attempt_log end,
  updated_at = now()
 where id = p_id;
 return jsonb_build_object('state', 'published', 'blog_id', v_blog);
end $$;

-- Asks for a new photograph. Idempotent while a request is open. Only a
-- preview or a post live for less than eight days qualifies, only when its
-- art direction exists, and never past the per-slot cap.
create function public.request_journal_editorial_image(p_id uuid, p_actor text)
returns text language plpgsql security invoker set search_path = '' as $$
declare a public.journal_editorial_assignments;
begin
 select * into a from public.journal_editorial_assignments where id = p_id for update;
 if not found then return 'NOT_FOUND'; end if;
 if a.state not in ('scheduled', 'published')
  or (a.state = 'published' and a.published_at < now() - interval '8 days') then
  return 'NOT_ELIGIBLE';
 end if;
 if coalesce(btrim(a.package->'article'->>'image_prompt'), '') = '' then return 'NO_IMAGE_PROMPT'; end if;
 if a.image_requested_at is not null then return 'requested'; end if;
 if a.image_generations >= 8 then return 'IMAGE_LIMIT'; end if;
 update public.journal_editorial_assignments set
  image_requested_at = now(), image_requested_by = left(coalesce(p_actor, ''), 200), image_failures = 0,
  attempt_log = case when jsonb_array_length(attempt_log) < 40 then attempt_log || jsonb_build_array(jsonb_build_object(
   'event', 'image_requested', 'actor', left(coalesce(p_actor, ''), 200), 'at', now()))
   else attempt_log end,
  updated_at = now()
 where id = p_id;
 return 'requested';
end $$;

-- Fulfils an open request: the preview changes, and a published post's
-- photograph changes with it in the same transaction.
create function public.replace_journal_editorial_image(p_id uuid, p_preview jsonb)
returns text language plpgsql security invoker set search_path = '' as $$
declare a public.journal_editorial_assignments;
begin
 if p_preview is null or coalesce(p_preview->>'url', '') !~ '^https://' then
  raise exception 'Replacement requires a public image';
 end if;
 select * into a from public.journal_editorial_assignments where id = p_id for update;
 if not found or a.image_requested_at is null or a.state not in ('scheduled', 'published') then return null; end if;
 update public.journal_editorial_assignments set
  preview = p_preview, image_generations = least(image_generations + 1, 8),
  image_requested_at = null, image_requested_by = null, image_failures = 0,
  attempt_log = case when jsonb_array_length(attempt_log) < 40 then attempt_log || jsonb_build_array(jsonb_build_object(
   'event', 'image_replaced', 'sha256', p_preview->>'sha256', 'at', now()))
   else attempt_log end,
  updated_at = now()
 where id = p_id;
 if a.state = 'published' and a.blog_id is not null then
  update public.blog_posts set
   thumbnail_url = p_preview->>'url',
   image_prompt = coalesce(nullif(a.package->'article'->>'image_prompt', ''), image_prompt),
   updated_at = now()
  where id = a.blog_id;
 end if;
 return a.state;
end $$;

-- A failed generation keeps the request for the next tick. The third failure
-- closes it, keeps the current photograph, and tells the operator once.
create function public.fail_journal_editorial_image(
 p_id uuid, p_code text, p_user_id text, p_company_id text, p_title text, p_body text)
returns text language plpgsql security invoker set search_path = '' as $$
declare a public.journal_editorial_assignments; v_failures integer;
begin
 if p_code is null or p_code !~ '^[A-Z_]{1,80}$' then raise exception 'Invalid image code'; end if;
 select * into a from public.journal_editorial_assignments where id = p_id for update;
 if not found or a.image_requested_at is null then return null; end if;
 v_failures := least(a.image_failures + 1, 3);
 update public.journal_editorial_assignments set
  image_failures = v_failures,
  image_requested_at = case when v_failures >= 3 then null else image_requested_at end,
  image_requested_by = case when v_failures >= 3 then null else image_requested_by end,
  attempt_log = case when jsonb_array_length(attempt_log) < 40 then attempt_log || jsonb_build_array(jsonb_build_object(
   'event', 'image_failed', 'code', p_code, 'failures', v_failures, 'at', now()))
   else attempt_log end,
  updated_at = now()
 where id = p_id;
 if v_failures < 3 then return 'retry'; end if;
 if coalesce(p_user_id, '') <> '' and coalesce(p_company_id, '') <> '' and p_title is not null then
  insert into public.notifications (user_id, company_id, type, title, body, is_read, persistent, action_url, action_label, dedupe_key)
  values (p_user_id, p_company_id, 'journal_editorial', p_title, p_body, false, false,
   '/admin/blog?journal=' || p_id::text, 'OPEN',
   'journal:' || a.identity || ':image-failed:' || a.image_generations::text)
  on conflict do nothing;
 end if;
 return 'dropped';
end $$;

revoke all on function
 public.request_journal_editorial_image(uuid, text),
 public.replace_journal_editorial_image(uuid, jsonb),
 public.fail_journal_editorial_image(uuid, text, text, text, text, text)
from public, anon, authenticated;
grant execute on function
 public.request_journal_editorial_image(uuid, text),
 public.replace_journal_editorial_image(uuid, jsonb),
 public.fail_journal_editorial_image(uuid, text, text, text, text, text)
to service_role;
