import type { SocialPostRecord } from "@/lib/social/types";

export function socialPostFixture(overrides: Partial<SocialPostRecord> = {}): SocialPostRecord {
  const now = "2026-09-01T20:00:00.000Z";
  return {
    id: "d88f06bd-985a-4c66-a609-1e85f9dc6803",
    idempotency_key: "blog-d88f06bd-v1",
    contract_version: "2026-09-01",
    source_type: "blog",
    source_id: "9d5fd8b8-83bc-44bf-b846-63c5a1bb9c30",
    source_url: "https://opsapp.ca/blog/the-two-hour-leak",
    story_type: "blog_signal",
    visual_treatment: "operator_brief",
    post_format: "single",
    content: {
      title: "The two-hour leak in your week",
      hook: "Your crew is waiting on an answer you already gave once.",
      angle: "Show the cost of repeated coordination and the practical fix.",
      caption: "Every repeated answer costs attention. Put the plan where the crew works.",
      alt_text: "A field note about repeated crew coordination.",
      slides: [
        {
          headline: "The two-hour leak in your week",
          body: "Every repeated answer costs attention, time, and margin.",
        },
      ],
    },
    caption: "Every repeated answer costs attention. Put the plan where the crew works.",
    alt_text: "A field note about repeated crew coordination.",
    agent_preferences: {},
    selection_metadata: {},
    rendered_assets: [
      {
        order: 1,
        url: "https://cdn.opsapp.ca/social/slide-1.jpg",
        alt_text: "A field note about repeated crew coordination.",
        sha256: "abc",
        width: 1080,
        height: 1350,
        bytes: 123,
        content_type: "image/jpeg",
        storage_key: "social-media/post/render/slide-01.jpg",
      },
    ],
    status: "publishing",
    publish_after: "2026-09-01T19:59:00.000Z",
    requested_publish_at: null,
    rendered_at: "2026-09-01T19:50:00.000Z",
    published_at: null,
    cancelled_at: null,
    attempt_count: 1,
    max_attempts: 3,
    next_attempt_at: null,
    last_attempt_at: now,
    claim_token: "0749af28-5852-4728-a36c-4f222a3e4b92",
    claim_expires_at: "2026-09-01T20:03:00.000Z",
    last_error_code: null,
    last_error_message: null,
    last_error_retryable: null,
    instagram_media_id: null,
    instagram_permalink: null,
    render_version: "social-render-2026-09-01-v1",
    selector_version: "feed-cycle-2026-09-01",
    voice_reference_version: "ops-social-parr-2026-09-01",
    created_by: "agent:social",
    updated_by: "system:publisher",
    audit_log: [],
    created_at: "2026-09-01T19:49:00.000Z",
    updated_at: now,
    ...overrides,
  };
}
