"use client";

import { Check, Globe, Loader2, Save } from "lucide-react";
import { cn } from "@/lib/utils/cn";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useCompanySettings, useUpdateCompanySettings } from "@/lib/hooks";
import { usePreferencesStore, type DashboardLayoutId, type SchedulingTypeId } from "@/stores/preferences-store";
// Note: Notification preferences moved to dedicated notifications-tab.tsx (server-persisted)
import { toast } from "sonner";
import { useLocale, useDictionary } from "@/i18n/client";
import type { Locale } from "@/i18n/types";

function LanguageCard() {
  const { locale, setLocale } = useLocale();
  const { t } = useDictionary("settings");
  const options: { id: Locale; label: string }[] = [
    { id: "en", label: "English" },
    { id: "es", label: "Español" },
  ];

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Globe className="w-[16px] h-[16px] text-text-secondary" />
          <CardTitle>{t("preferences.language")} / {t("preferences.idioma")}</CardTitle>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex gap-2">
          {options.map((opt) => (
            <button
              key={opt.id}
              onClick={() => {
                if (opt.id !== locale) setLocale(opt.id);
              }}
              className={cn(
                "flex-1 px-3 py-2 rounded border text-center font-mohave text-body transition-all",
                locale === opt.id
                  ? "bg-ops-accent-muted border-ops-accent text-text-primary"
                  : "bg-background-input border-border text-text-secondary hover:border-border-medium"
              )}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

function LifecycleSettings() {
  const { t } = useDictionary("settings");
  const { data: settings, isLoading } = useCompanySettings();
  const updateSettings = useUpdateCompanySettings();

  function handleToggle(key: "autoGenerateTasks" | "gmailAutoLogEnabled", currentValue: boolean) {
    updateSettings.mutate(
      { [key]: !currentValue },
      {
        onSuccess: () => toast.success(t("preferences.toast.settingUpdated")),
        onError: (err) => toast.error(t("preferences.toast.updateFailed"), { description: err.message }),
      }
    );
  }

  function handleFollowUpDays(value: string) {
    const days = parseInt(value, 10);
    if (isNaN(days) || days < 1) return;
    updateSettings.mutate(
      { followUpReminderDays: days },
      {
        onSuccess: () => toast.success(t("preferences.toast.followUpUpdated")),
        onError: (err) => toast.error(t("preferences.toast.updateFailed"), { description: err.message }),
      }
    );
  }

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-4">
          <Loader2 className="w-[20px] h-[20px] text-ops-accent animate-spin" />
        </CardContent>
      </Card>
    );
  }

  const autoGenerate = settings?.autoGenerateTasks ?? false;
  const followUpDays = settings?.followUpReminderDays ?? 3;
  const gmailAutoLog = settings?.gmailAutoLogEnabled ?? true;

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t("preferences.lifecycle")}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text-primary">{t("preferences.autoGenerate")}</p>
            <p className="font-kosugi text-[11px] text-text-disabled">
              {t("preferences.autoGenerateDesc")}
            </p>
          </div>
          <button
            onClick={() => handleToggle("autoGenerateTasks", autoGenerate)}
            className={cn(
              "w-[40px] h-[22px] rounded-full transition-colors relative shrink-0",
              autoGenerate ? "bg-ops-accent" : "bg-background-elevated"
            )}
          >
            <span
              className={cn(
                "absolute top-[2px] w-[18px] h-[18px] rounded-full bg-white transition-all",
                autoGenerate ? "right-[2px]" : "left-[2px]"
              )}
            />
          </button>
        </div>

        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text-primary">{t("preferences.followUpReminder")}</p>
            <p className="font-kosugi text-[11px] text-text-disabled">
              {t("preferences.followUpDesc")}
            </p>
          </div>
          <div className="flex items-center gap-[6px] shrink-0">
            <Input
              type="number"
              min={1}
              max={30}
              value={followUpDays}
              onChange={(e) => handleFollowUpDays(e.target.value)}
              className="w-[56px] h-[32px] text-center"
            />
            <span className="font-mohave text-body-sm text-text-tertiary">{t("preferences.days")}</span>
          </div>
        </div>

        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text-primary">{t("preferences.gmailAutoLog")}</p>
            <p className="font-kosugi text-[11px] text-text-disabled">
              {t("preferences.gmailAutoLogDesc")}
            </p>
          </div>
          <button
            onClick={() => handleToggle("gmailAutoLogEnabled", gmailAutoLog)}
            className={cn(
              "w-[40px] h-[22px] rounded-full transition-colors relative shrink-0",
              gmailAutoLog ? "bg-ops-accent" : "bg-background-elevated"
            )}
          >
            <span
              className={cn(
                "absolute top-[2px] w-[18px] h-[18px] rounded-full bg-white transition-all",
                gmailAutoLog ? "right-[2px]" : "left-[2px]"
              )}
            />
          </button>
        </div>
      </CardContent>
    </Card>
  );
}

export function PreferencesTab() {
  const { t } = useDictionary("settings");
  const dashboardLayout = usePreferencesStore((s) => s.dashboardLayout);
  const setDashboardLayout = usePreferencesStore((s) => s.setDashboardLayout);
  const schedulingType = usePreferencesStore((s) => s.schedulingType);
  const setSchedulingType = usePreferencesStore((s) => s.setSchedulingType);
  const schedulingTypes: { id: SchedulingTypeId; label: string; description: string }[] = [
    { id: "all-day", label: t("preferences.schedAllDay"), description: t("preferences.schedAllDayDesc") },
    { id: "time-slots", label: t("preferences.schedTimeSlots"), description: t("preferences.schedTimeSlotsDesc") },
    { id: "both", label: t("preferences.schedBoth"), description: t("preferences.schedBothDesc") },
  ];

  const layouts: { id: DashboardLayoutId; label: string; description: string }[] = [
    { id: "default", label: t("preferences.layoutDefault"), description: t("preferences.layoutDefaultDesc") },
    { id: "compact", label: t("preferences.layoutCompact"), description: t("preferences.layoutCompactDesc") },
    { id: "data-dense", label: t("preferences.layoutDataDense"), description: t("preferences.layoutDataDenseDesc") },
  ];

  return (
    <div className="space-y-3 max-w-[600px]">
      <LanguageCard />
      <LifecycleSettings />

      <Card>
        <CardHeader>
          <CardTitle>{t("preferences.dashboardLayout")}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-1">
            {layouts.map((layout) => (
              <button
                key={layout.id}
                onClick={() => {
                  setDashboardLayout(layout.id);
                  toast.success(`${t("preferences.toast.layoutSet")} ${layout.label}`);
                }}
                className={cn(
                  "w-full flex items-center justify-between px-1.5 py-1 rounded border transition-all",
                  dashboardLayout === layout.id
                    ? "bg-ops-accent-muted border-ops-accent"
                    : "bg-background-input border-border hover:border-border-medium"
                )}
              >
                <div>
                  <p className="font-mohave text-body text-text-primary text-left">{layout.label}</p>
                  <p className="font-kosugi text-[11px] text-text-tertiary">{layout.description}</p>
                </div>
                {dashboardLayout === layout.id && (
                  <div className="w-[20px] h-[20px] rounded-full bg-ops-accent flex items-center justify-center">
                    <Check className="w-[12px] h-[12px] text-white" />
                  </div>
                )}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>{t("preferences.schedulingType")}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-1">
            {schedulingTypes.map((type) => (
              <button
                key={type.id}
                onClick={() => {
                  setSchedulingType(type.id);
                  toast.success(`${t("preferences.toast.schedulingSet")} ${type.label}`);
                }}
                className={cn(
                  "w-full flex items-center justify-between px-1.5 py-1 rounded border transition-all",
                  schedulingType === type.id
                    ? "bg-ops-accent-muted border-ops-accent"
                    : "bg-background-input border-border hover:border-border-medium"
                )}
              >
                <div>
                  <p className="font-mohave text-body text-text-primary text-left">{type.label}</p>
                  <p className="font-kosugi text-[11px] text-text-tertiary">{type.description}</p>
                </div>
                {schedulingType === type.id && (
                  <div className="w-[20px] h-[20px] rounded-full bg-ops-accent flex items-center justify-center">
                    <Check className="w-[12px] h-[12px] text-white" />
                  </div>
                )}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

    </div>
  );
}
