"use client";

import { Check, Globe, Loader2, Zap } from "lucide-react";
import { cn } from "@/lib/utils/cn";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { SegmentControl } from "@/components/ui/segment-control";
import { Switch } from "@/components/ui/switch";
import { useCompanySettings, useUpdateCompanySettings } from "@/lib/hooks";
import { usePreferencesStore, type DashboardLayoutId, type SchedulingTypeId } from "@/stores/preferences-store";
import { useAuthStore } from "@/lib/store/auth-store";
import { ALL_ACTIONS, DEFAULT_ACTION_IDS } from "@/lib/constants/fab-actions";
import { toast } from "sonner";
import { useLocale, useDictionary } from "@/i18n/client";
import type { Locale } from "@/i18n/types";

// ─── Section header (// TITLE) ───────────────────────────────────────────────

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <span className="font-mono text-micro uppercase tracking-[0.16em] text-text-3">
      <span className="text-text-mute">{"// "}</span>
      {children}
    </span>
  );
}

function LanguageCard() {
  const { locale, setLocale } = useLocale();
  const { t } = useDictionary("settings");
  const options: { value: Locale; label: string }[] = [
    { value: "en", label: "English" },
    { value: "es", label: "Español" },
  ];

  return (
    <Card>
      <div className="flex items-center gap-2 pb-2">
        <Globe className="w-[16px] h-[16px] text-text-2" />
        <SectionTitle>
          {t("preferences.language")} / {t("preferences.idioma")}
        </SectionTitle>
      </div>
      <CardContent>
        <SegmentControl<Locale>
          options={options}
          value={locale}
          onChange={(v) => {
            if (v !== locale) setLocale(v);
          }}
        />
      </CardContent>
    </Card>
  );
}

function LifecycleSettings() {
  const { t } = useDictionary("settings");
  const { data: settings, isLoading } = useCompanySettings();
  const updateSettings = useUpdateCompanySettings();

  function handleToggle(key: "autoGenerateTasks" | "gmailAutoLogEnabled", currentValue: boolean) {
    updateSettings.mutate(
      { [key]: !currentValue },
      {
        onSuccess: () => toast.success(t("preferences.toast.settingUpdated")),
        onError: (err) => toast.error(t("preferences.toast.updateFailed"), { description: err.message }),
      }
    );
  }

  function handleFollowUpDays(value: string) {
    const days = parseInt(value, 10);
    if (isNaN(days) || days < 1) return;
    updateSettings.mutate(
      { followUpReminderDays: days },
      {
        onSuccess: () => toast.success(t("preferences.toast.followUpUpdated")),
        onError: (err) => toast.error(t("preferences.toast.updateFailed"), { description: err.message }),
      }
    );
  }

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-4">
          <Loader2 className="w-[20px] h-[20px] text-text-2 animate-spin" />
        </CardContent>
      </Card>
    );
  }

  const autoGenerate = settings?.autoGenerateTasks ?? false;
  const followUpDays = settings?.followUpReminderDays ?? 3;
  const gmailAutoLog = settings?.gmailAutoLogEnabled ?? true;

  return (
    <Card>
      <div className="pb-2">
        <SectionTitle>{t("preferences.lifecycle")}</SectionTitle>
      </div>
      <CardContent className="space-y-2">
        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text">{t("preferences.autoGenerate")}</p>
            <p className="font-mono text-micro text-text-mute">
              {t("preferences.autoGenerateDesc")}
            </p>
          </div>
          <Switch
            checked={autoGenerate}
            onCheckedChange={() => handleToggle("autoGenerateTasks", autoGenerate)}
          />
        </div>

        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text">{t("preferences.followUpReminder")}</p>
            <p className="font-mono text-micro text-text-mute">
              {t("preferences.followUpDesc")}
            </p>
          </div>
          <div className="flex items-center gap-[6px] shrink-0">
            <Input
              type="number"
              min={1}
              max={30}
              value={followUpDays}
              onChange={(e) => handleFollowUpDays(e.target.value)}
              className="w-[64px] text-center font-mono tabular-nums"
            />
            <span className="font-mohave text-body-sm text-text-3">{t("preferences.days")}</span>
          </div>
        </div>

        <div className="flex items-center justify-between py-[6px]">
          <div>
            <p className="font-mohave text-body text-text">{t("preferences.gmailAutoLog")}</p>
            <p className="font-mono text-micro text-text-mute">
              {t("preferences.gmailAutoLogDesc")}
            </p>
          </div>
          <Switch
            checked={gmailAutoLog}
            onCheckedChange={() => handleToggle("gmailAutoLogEnabled", gmailAutoLog)}
          />
        </div>
      </CardContent>
    </Card>
  );
}

function QuickActionsCard() {
  const { t } = useDictionary("settings");
  const { t: tQuickActions } = useDictionary("quick-actions");
  const { currentUser, updateFabActions } = useAuthStore();
  const activeIds: string[] = currentUser?.fabActions ?? DEFAULT_ACTION_IDS;

  function toggle(id: string) {
    const isActive = activeIds.includes(id);
    if (isActive) {
      if (activeIds.length <= 1) return;
      updateFabActions(activeIds.filter((a) => a !== id));
    } else {
      updateFabActions([...activeIds, id]);
    }
  }

  return (
    <Card>
      <div className="flex flex-col gap-0.5 pb-2">
        <div className="flex items-center gap-2">
          <Zap className="w-[16px] h-[16px] text-text-2" />
          <SectionTitle>{t("sections.quickActions")}</SectionTitle>
        </div>
        <p className="font-mono text-micro text-text-mute">
          {t("preferences.quickActionsDesc")}
        </p>
      </div>
      <CardContent className="p-0">
        {ALL_ACTIONS.map((action, index) => {
          const Icon = action.icon;
          const isActive = activeIds.includes(action.id);
          const isLast = index === ALL_ACTIONS.length - 1;

          return (
            <div
              key={action.id}
              className={cn(
                "flex items-center gap-2 px-2 py-[8px]",
                !isLast && "border-b border-[rgba(255,255,255,0.04)]"
              )}
            >
              <Icon className="w-[16px] h-[16px] text-text-2 shrink-0" />
              <span className="font-mohave text-[14px] text-text flex-1">
                {tQuickActions(action.labelKey)}
              </span>
              <Switch
                checked={isActive}
                disabled={isActive && activeIds.length <= 1}
                onCheckedChange={() => toggle(action.id)}
              />
            </div>
          );
        })}
      </CardContent>
    </Card>
  );
}

export function PreferencesTab() {
  const { t } = useDictionary("settings");
  const dashboardLayout = usePreferencesStore((s) => s.dashboardLayout);
  const setDashboardLayout = usePreferencesStore((s) => s.setDashboardLayout);
  const schedulingType = usePreferencesStore((s) => s.schedulingType);
  const setSchedulingType = usePreferencesStore((s) => s.setSchedulingType);
  const schedulingTypes: { id: SchedulingTypeId; label: string; description: string }[] = [
    { id: "all-day", label: t("preferences.schedAllDay"), description: t("preferences.schedAllDayDesc") },
    { id: "time-slots", label: t("preferences.schedTimeSlots"), description: t("preferences.schedTimeSlotsDesc") },
    { id: "both", label: t("preferences.schedBoth"), description: t("preferences.schedBothDesc") },
  ];

  const layouts: { id: DashboardLayoutId; label: string; description: string }[] = [
    { id: "default", label: t("preferences.layoutDefault"), description: t("preferences.layoutDefaultDesc") },
    { id: "compact", label: t("preferences.layoutCompact"), description: t("preferences.layoutCompactDesc") },
    { id: "data-dense", label: t("preferences.layoutDataDense"), description: t("preferences.layoutDataDenseDesc") },
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
      <LanguageCard />
      <LifecycleSettings />

      <Card>
        <div className="pb-2">
          <SectionTitle>{t("preferences.dashboardLayout")}</SectionTitle>
        </div>
        <CardContent>
          <div className="space-y-1">
            {layouts.map((layout) => {
              const isActive = dashboardLayout === layout.id;
              return (
                <button
                  key={layout.id}
                  onClick={() => {
                    setDashboardLayout(layout.id);
                    toast.success(`${t("preferences.toast.layoutSet")} ${layout.label}`);
                  }}
                  className={cn(
                    "w-full flex items-center justify-between px-1.5 py-1 rounded border transition-all",
                    isActive
                      ? "bg-surface-active border-[rgba(255,255,255,0.18)]"
                      : "bg-surface-input border-border hover:border-border-medium"
                  )}
                >
                  <div>
                    <p className="font-mohave text-body text-text text-left">{layout.label}</p>
                    <p className="font-mono text-micro text-text-3">{layout.description}</p>
                  </div>
                  {isActive && (
                    <div className="w-[20px] h-[20px] rounded-full bg-text-2 flex items-center justify-center shrink-0">
                      <Check className="w-[12px] h-[12px] text-background" />
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <Card>
        <div className="pb-2">
          <SectionTitle>{t("preferences.schedulingType")}</SectionTitle>
        </div>
        <CardContent>
          <div className="space-y-1">
            {schedulingTypes.map((type) => {
              const isActive = schedulingType === type.id;
              return (
                <button
                  key={type.id}
                  onClick={() => {
                    setSchedulingType(type.id);
                    toast.success(`${t("preferences.toast.schedulingSet")} ${type.label}`);
                  }}
                  className={cn(
                    "w-full flex items-center justify-between px-1.5 py-1 rounded border transition-all",
                    isActive
                      ? "bg-surface-active border-[rgba(255,255,255,0.18)]"
                      : "bg-surface-input border-border hover:border-border-medium"
                  )}
                >
                  <div>
                    <p className="font-mohave text-body text-text text-left">{type.label}</p>
                    <p className="font-mono text-micro text-text-3">{type.description}</p>
                  </div>
                  {isActive && (
                    <div className="w-[20px] h-[20px] rounded-full bg-text-2 flex items-center justify-center shrink-0">
                      <Check className="w-[12px] h-[12px] text-background" />
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <QuickActionsCard />
    </div>
  );
}
