import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const SUFFIX = "_agent_operational_overview_read.sql";
const migrationNames = readdirSync(
  join(process.cwd(), "supabase/migrations")
).filter((name) => name.endsWith(SUFFIX));
const MIGRATION = readFileSync(
  join(process.cwd(), "supabase/migrations", migrationNames[0] ?? "MISSING"),
  "utf8"
);
const BODY = readFileSync(
  join(
    process.cwd(),
    "src/lib/agent-control-plane/services/p2/overview/sql/agent_operational_overview_read.body.sql"
  ),
  "utf8"
);
const RUNTIME = readFileSync(
  join(process.cwd(), "tests/sql/agent-operational-overview-runtime.sql"),
  "utf8"
);
const REPLAY = readFileSync(
  join(
    process.cwd(),
    "tests/sql/agent-operational-overview-replay-runtime.sql"
  ),
  "utf8"
);
const SQL = MIGRATION.toLowerCase();
const COMPACT = SQL.replace(/\s+/g, " ").trim();

describe("P2 operational-overview read migration", () => {
  it("uses one generated byte-identical transactional migration", () => {
    expect(migrationNames).toHaveLength(1);
    expect(migrationNames[0]).toMatch(
      /^\d{14}_agent_operational_overview_read\.sql$/
    );
    expect(MIGRATION).toBe(BODY);
    expect(SQL).toMatch(/(?:^|\n)begin;\s/);
    expect(SQL.trim().endsWith("commit;")).toBe(true);
    expect(SQL).toContain("do $prerequisites$");
    expect(SQL).toContain("do $canonical_acl$");
    expect(SQL).toContain("do $postflight$");
    expect(SQL.match(/owner to current_user/g)).toHaveLength(5);
    expect(SQL).not.toMatch(/\b(insert|update|delete|merge|truncate)\b/i);
  });

  it("keeps composition private and grants only the fixed service RPC", () => {
    expect(COMPACT).toContain(
      "create or replace function private.agent_p2_operational_overview_summary_v1("
    );
    expect(COMPACT).toContain(
      "create or replace function public.read_agent_operational_overview_as_system("
    );
    expect(COMPACT).toContain(
      "language plpgsql stable security definer set search_path = ''"
    );
    expect(COMPACT.match(/grant execute on function/g)).toHaveLength(1);
    expect(COMPACT).toContain(
      "grant execute on function public.read_agent_operational_overview_as_system("
    );
    for (const forbidden of ["grant select", "set role", "current_setting("]) {
      expect(COMPACT).not.toContain(forbidden);
    }
  });

  it("re-proves every selected component independently and omits only denied defaults", () => {
    for (const expected of [
      "p_capability_id is distinct from 'get_operational_overview'",
      "p_capability_revision is distinct from 'get_operational_overview:2026-08-22.v1'",
      "p_capability_manifest_revision is distinct from '2026-08-22.capability-manifest.v8'",
      "private.agent_p2_operational_overview_expected_component_v1(",
      "selection.origin = 'explicit' and selection.expected is null",
      "'code', 'default_component_omitted'",
      "p_authorized_components is distinct from v_expected_authorized",
      "p_warnings is distinct from v_expected_warnings",
      "grant_row.scopes = p_granted_scope_ceiling",
      "grant_row.revoked_at is null",
      "oauth_client.disabled_at is null",
      "actor.deleted_at is null",
      "actor.is_active is true",
    ]) {
      expect(COMPACT).toContain(expected);
    }
  });

  it("pins the six canonical selections and exact 25/26/501 boundaries", () => {
    for (const component of [
      "financial_attention",
      "integration_attention",
      "schedule_readiness",
      "stock_attention",
      "unresolved_correspondence",
      "work_due",
    ]) {
      expect(COMPACT).toContain(`'${component}'`);
    }
    for (const expected of [
      "p_item_limit is distinct from 25",
      "p_page_fetch_limit is distinct from 26",
      "p_source_limit is distinct from 501",
      "pg_catalog.jsonb_array_length(p_selections) not between 1 and 6",
      "selection.value ->> 'origin' = 'default'",
      "pg_catalog.jsonb_array_length(p_selections) <> 6",
    ]) {
      expect(COMPACT).toContain(expected);
    }
  });

  it("composes only pinned private attention projections without a broad business scan", () => {
    for (const helper of [
      "private.agent_p2_sales_document_attention_v1(",
      "private.agent_p2_payment_attention_v1(",
      "private.agent_p2_expense_attention_v1(",
      "private.agent_p2_catalog_attention_v1(",
      "private.agent_p2_purchase_order_attention_v1(",
      "private.agent_p2_integration_health_summary_v1(",
      "private.agent_p2_legacy_schedule_attention_v1(",
      "private.agent_p2_work_queue_attention_v1(",
    ]) {
      expect(COMPACT).toContain(helper);
    }
    for (const forbidden of [
      "from public.project_tasks",
      "from public.email_connections",
      "from public.accounting_connections",
      "from public.expenses",
      "from public.catalog_orders",
      "from public.invoices",
      "from public.payments",
    ]) {
      expect(COMPACT).not.toContain(forbidden);
    }
  });

  it("binds component-local revisions and the canonical aggregate proof union", () => {
    for (const expected of [
      "'proof_kind', 'operational_overview_entity'",
      "'proof_kind', 'operational_overview_evidence'",
      "'proof_kind', 'operational_overview_collection'",
      "'component_authorization'",
      "'source_revisions', v_component_revisions",
      "'source_revisions', v_source_revisions",
      "'component_source_inspected', v_component_source_inspected",
      "'source_inspected', v_component_inspected",
      "'request_id', p_request_id",
      "private.canonical_agent_projection_json(",
      "'returned_count', pg_catalog.jsonb_array_length(v_rows)",
      "'has_more', false",
    ]) {
      expect(COMPACT).toContain(expected);
    }
    expect(COMPACT).toContain("'source_inspected', v_source_inspected");
    for (const cap of [
      "when 'financial_attention' then 1000",
      "when 'integration_attention' then 1000",
      "when 'schedule_readiness' then 500",
      "when 'stock_attention' then 2500",
      "when 'unresolved_correspondence' then 4500",
      "when 'work_due' then 4500",
      "(v_purchase_overdue #>> '{source_inspected,orders}')::integer >= p_source_limit",
      "(v_purchase_overdue #>> '{source_inspected,lines}')::integer >= p_source_limit",
      "(v_purchase_due_soon #>> '{source_inspected,orders}')::integer >= p_source_limit",
      "(v_purchase_due_soon #>> '{source_inspected,lines}')::integer >= p_source_limit",
    ]) {
      expect(COMPACT).toContain(cap);
    }
    for (const exactVector of [
      "array[ 'expenses', 'legacy_operational', 'payments', 'sales_documents' ]::text[]",
      "array['company', 'integrations']::text[]",
      "array['catalog', 'purchasing']::text[]",
      "'legacy_job_history', 'legacy_operational', 'work_queue'",
      "'legacy_operational', 'tasks', 'work_queue'",
    ]) {
      expect(COMPACT).toContain(exactVector);
    }
  });

  it("returns only coarse count states and canonical overview errors", () => {
    for (const expected of [
      "'attention_count'",
      "'count_state'",
      "'at_least_limit'",
      "'state'",
      "'clear'",
      "'attention'",
      "raise exception 'agent_operational_overview_source_query_bound' using errcode = '54000'",
      "raise exception 'agent_operational_overview_source_data_invalid' using errcode = '22000'",
    ]) {
      expect(COMPACT).toContain(expected);
    }
    for (const forbiddenKey of [
      "'title'",
      "'notes'",
      "'subject'",
      "'merchant_name'",
      "'customer_ref'",
      "'job_ref'",
      "'task_ref'",
      "'thread_ref'",
    ]) {
      expect(COMPACT).not.toContain(forbiddenKey);
    }
  });

  it("ships rollback-only PG17 behavior and hostile ACL replay proofs", () => {
    for (const expected of [
      "agent_mcp_operational_overview_bootstrap",
      "server_version_num",
      "source_inspected')::integer <> 61",
      "set_config('timezone','asia/kathmandu'",
      "agent_operational_overview_source_query_bound",
      "overview-runtime-explicit-denied",
      "overview-runtime-purchase-orders-bound",
      "overview-runtime-purchase-lines-bound",
      "rollback;",
    ]) {
      expect(RUNTIME.toLowerCase()).toContain(expected);
    }
    for (const expected of [
      "to pg_monitor with grant option",
      "20260829110002_agent_operational_overview_read.sql",
      "has_function_privilege('pg_monitor'",
      "agent_operational_overview_replay_failed: dml",
      "service_role:execute:false",
      "rollback;",
    ]) {
      expect(REPLAY.toLowerCase()).toContain(expected);
    }
  });
});
