import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const SUFFIX = "_agent_integration_health_sources.sql";
const migrationNames = readdirSync(
  join(process.cwd(), "supabase/migrations")
).filter((name) => name.endsWith(SUFFIX));
const MIGRATION = readFileSync(
  join(process.cwd(), "supabase/migrations", migrationNames[0] ?? "MISSING"),
  "utf8"
);
const BODY = readFileSync(
  join(
    process.cwd(),
    "src/lib/agent-control-plane/services/p2/integrations/sql/agent_integration_health_sources.body.sql"
  ),
  "utf8"
);
const SQL = MIGRATION.toLowerCase();
const COMPACT = SQL.replace(/\s+/g, " ").trim();

describe("P2 integration-health source fence migration", () => {
  it("uses one generated byte-identical transactional migration", () => {
    expect(migrationNames).toHaveLength(1);
    expect(migrationNames[0]).toMatch(
      /^\d{14}_agent_integration_health_sources\.sql$/
    );
    expect(MIGRATION).toBe(BODY);
    expect(SQL).toMatch(/(?:^|\n)begin;\s/);
    expect(SQL.trim().endsWith("commit;")).toBe(true);
    expect(SQL).toContain("do $prerequisites$");
    expect(SQL).toContain("do $source_shape$");
    expect(SQL).toContain("do $postflight$");
  });

  it("advances only integrations for every health-affecting source change", () => {
    expect(COMPACT).toContain(
      "create trigger email_connections_bump_agent_integrations_revision"
    );
    expect(COMPACT).toContain(
      "create trigger accounting_connections_bump_agent_integrations_revision"
    );
    expect(COMPACT.match(/'integrations', 'company_id'/g)).toHaveLength(2);
    for (const column of [
      "status",
      "sync_enabled",
      "webhook_subscription_id",
      "webhook_expires_at",
      "last_synced_at",
      "provider_snapshot_at",
      "granted_scopes",
      "created_at",
      "provider_environment",
      "is_connected",
      "last_sync_at",
    ]) {
      expect(COMPACT).toContain(column);
    }
  });

  it("pins exact source types and bounded keyset indexes without source grants", () => {
    for (const indexName of [
      "idx_email_connections_agent_integration_health_v1",
      "idx_accounting_connections_agent_integration_health_v1",
    ]) {
      expect(COMPACT).toContain(`create index if not exists ${indexName}`);
    }
    expect(COMPACT).toContain("where provider_environment = 'production'");
    for (const forbidden of [
      "grant select",
      "grant all",
      "create or replace function public.",
    ]) {
      expect(COMPACT).not.toContain(forbidden);
    }
  });
});
